"""
C1 Level Vocabulary - Advanced
Alliance Française C100-C105 equivalent
Expanded content for sustained practice sessions
"""

VOCABULARY_C1 = [
    # Academic & Intellectual (25 items)
    {"french": "l'analyse", "english": "analysis", "spanish": "el análisis", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "análisis"},
    {"french": "la synthèse", "english": "synthesis/summary", "spanish": "la síntesis", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "síntesis"},
    {"french": "la thèse", "english": "thesis/argument", "spanish": "la tesis", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "tesis"},
    {"french": "argumenter", "english": "to argue/present arguments", "spanish": "argumentar", "gender": "-", "part_of_speech": "verb", "category": "academic", "is_cognate": True, "cognate_spanish": "argumentar"},
    {"french": "nuancer", "english": "to nuance/qualify", "spanish": "matizar", "gender": "-", "part_of_speech": "verb", "category": "academic", "is_cognate": True, "cognate_spanish": "matizar"},
    {"french": "approfondir", "english": "to deepen/explore further", "spanish": "profundizar", "gender": "-", "part_of_speech": "verb", "category": "academic", "is_cognate": True, "cognate_spanish": "profundizar"},
    {"french": "la problématique", "english": "issue/problematic", "spanish": "la problemática", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "problemática"},
    {"french": "l'hypothèse", "english": "hypothesis", "spanish": "la hipótesis", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "hipótesis"},
    {"french": "la méthodologie", "english": "methodology", "spanish": "la metodología", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "metodología"},
    {"french": "le paradigme", "english": "paradigm", "spanish": "el paradigma", "gender": "m", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "paradigma"},
    {"french": "la corrélation", "english": "correlation", "spanish": "la correlación", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "correlación"},
    {"french": "la causalité", "english": "causality", "spanish": "la causalidad", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "causalidad"},
    {"french": "empirique", "english": "empirical", "spanish": "empírico", "gender": "-", "part_of_speech": "adjective", "category": "academic", "is_cognate": True, "cognate_spanish": "empírico"},
    {"french": "théorique", "english": "theoretical", "spanish": "teórico", "gender": "-", "part_of_speech": "adjective", "category": "academic", "is_cognate": True, "cognate_spanish": "teórico"},
    {"french": "élaborer", "english": "to elaborate/develop", "spanish": "elaborar", "gender": "-", "part_of_speech": "verb", "category": "academic", "is_cognate": True, "cognate_spanish": "elaborar"},
    {"french": "conceptualiser", "english": "to conceptualize", "spanish": "conceptualizar", "gender": "-", "part_of_speech": "verb", "category": "academic", "is_cognate": True, "cognate_spanish": "conceptualizar"},
    {"french": "le postulat", "english": "postulate", "spanish": "el postulado", "gender": "m", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "postulado"},
    {"french": "la prémisse", "english": "premise", "spanish": "la premisa", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "premisa"},
    {"french": "déduire", "english": "to deduce", "spanish": "deducir", "gender": "-", "part_of_speech": "verb", "category": "academic", "is_cognate": True, "cognate_spanish": "deducir"},
    {"french": "induire", "english": "to induce", "spanish": "inducir", "gender": "-", "part_of_speech": "verb", "category": "academic", "is_cognate": True, "cognate_spanish": "inducir"},
    {"french": "la démarche", "english": "approach/process", "spanish": "el proceso", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": False},
    {"french": "corroborer", "english": "to corroborate", "spanish": "corroborar", "gender": "-", "part_of_speech": "verb", "category": "academic", "is_cognate": True, "cognate_spanish": "corroborar"},
    {"french": "réfuter", "english": "to refute", "spanish": "refutar", "gender": "-", "part_of_speech": "verb", "category": "academic", "is_cognate": True, "cognate_spanish": "refutar"},
    {"french": "la rigueur", "english": "rigor", "spanish": "el rigor", "gender": "f", "part_of_speech": "noun", "category": "academic", "is_cognate": True, "cognate_spanish": "rigor"},
    {"french": "pertinent", "english": "relevant/pertinent", "spanish": "pertinente", "gender": "m", "part_of_speech": "adjective", "category": "academic", "is_cognate": True, "cognate_spanish": "pertinente"},

    # Philosophy & Ethics (20 items)
    {"french": "la conscience morale", "english": "moral conscience", "spanish": "la conciencia moral", "gender": "f", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "conciencia moral"},
    {"french": "l'éthique", "english": "ethics", "spanish": "la ética", "gender": "f", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "ética"},
    {"french": "la vertu", "english": "virtue", "spanish": "la virtud", "gender": "f", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "virtud"},
    {"french": "le libre arbitre", "english": "free will", "spanish": "el libre albedrío", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "libre albedrío"},
    {"french": "remettre en question", "english": "to question/challenge", "spanish": "poner en cuestión", "gender": "-", "part_of_speech": "verb", "category": "philosophy", "is_cognate": False},
    {"french": "l'existentialisme", "english": "existentialism", "spanish": "el existencialismo", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "existencialismo"},
    {"french": "le déterminisme", "english": "determinism", "spanish": "el determinismo", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "determinismo"},
    {"french": "l'aliénation", "english": "alienation", "spanish": "la alienación", "gender": "f", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "alienación"},
    {"french": "l'absurde", "english": "the absurd", "spanish": "el absurdo", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "absurdo"},
    {"french": "l'ontologie", "english": "ontology", "spanish": "la ontología", "gender": "f", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "ontología"},
    {"french": "l'épistémologie", "english": "epistemology", "spanish": "la epistemología", "gender": "f", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "epistemología"},
    {"french": "le relativisme", "english": "relativism", "spanish": "el relativismo", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "relativismo"},
    {"french": "l'utilitarisme", "english": "utilitarianism", "spanish": "el utilitarismo", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "utilitarismo"},
    {"french": "le rationalisme", "english": "rationalism", "spanish": "el racionalismo", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "racionalismo"},
    {"french": "l'empirisme", "english": "empiricism", "spanish": "el empirismo", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "empirismo"},
    {"french": "la métaphysique", "english": "metaphysics", "spanish": "la metafísica", "gender": "f", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "metafísica"},
    {"french": "le transcendantal", "english": "transcendental", "spanish": "lo trascendental", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "trascendental"},
    {"french": "l'immanence", "english": "immanence", "spanish": "la inmanencia", "gender": "f", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "inmanencia"},
    {"french": "le nihilisme", "english": "nihilism", "spanish": "el nihilismo", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "nihilismo"},
    {"french": "le stoïcisme", "english": "stoicism", "spanish": "el estoicismo", "gender": "m", "part_of_speech": "noun", "category": "philosophy", "is_cognate": True, "cognate_spanish": "estoicismo"},

    # Literary & Stylistic (20 items)
    {"french": "la métaphore", "english": "metaphor", "spanish": "la metáfora", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "metáfora"},
    {"french": "l'ironie", "english": "irony", "spanish": "la ironía", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "ironía"},
    {"french": "sous-entendre", "english": "to imply", "spanish": "dar a entender", "gender": "-", "part_of_speech": "verb", "category": "literary", "is_cognate": False},
    {"french": "l'ambiguïté", "english": "ambiguity", "spanish": "la ambigüedad", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "ambigüedad"},
    {"french": "le registre", "english": "register (language level)", "spanish": "el registro", "gender": "m", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "registro"},
    {"french": "l'allégorie", "english": "allegory", "spanish": "la alegoría", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "alegoría"},
    {"french": "l'hyperbole", "english": "hyperbole", "spanish": "la hipérbole", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "hipérbole"},
    {"french": "l'euphémisme", "english": "euphemism", "spanish": "el eufemismo", "gender": "m", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "eufemismo"},
    {"french": "la litote", "english": "understatement", "spanish": "la lítote", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "lítote"},
    {"french": "l'oxymore", "english": "oxymoron", "spanish": "el oxímoron", "gender": "m", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "oxímoron"},
    {"french": "la périphrase", "english": "periphrasis", "spanish": "la perífrasis", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "perífrasis"},
    {"french": "l'anaphore", "english": "anaphora", "spanish": "la anáfora", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "anáfora"},
    {"french": "la métonymie", "english": "metonymy", "spanish": "la metonimia", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "metonimia"},
    {"french": "le champ lexical", "english": "semantic field", "spanish": "el campo semántico", "gender": "m", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "campo"},
    {"french": "la connotation", "english": "connotation", "spanish": "la connotación", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "connotación"},
    {"french": "la dénotation", "english": "denotation", "spanish": "la denotación", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "denotación"},
    {"french": "le ton", "english": "tone", "spanish": "el tono", "gender": "m", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "tono"},
    {"french": "le récit", "english": "narrative", "spanish": "el relato", "gender": "m", "part_of_speech": "noun", "category": "literary", "is_cognate": False},
    {"french": "le narrateur", "english": "narrator", "spanish": "el narrador", "gender": "m", "part_of_speech": "noun", "category": "literary", "is_cognate": True, "cognate_spanish": "narrador"},
    {"french": "l'intrigue", "english": "plot", "spanish": "la trama", "gender": "f", "part_of_speech": "noun", "category": "literary", "is_cognate": False},

    # Formal Expressions (25 items)
    {"french": "en l'occurrence", "english": "in this case", "spanish": "en este caso", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": False},
    {"french": "en effet", "english": "indeed/in fact", "spanish": "en efecto", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": True, "cognate_spanish": "en efecto"},
    {"french": "voire", "english": "even/indeed", "spanish": "incluso", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": False},
    {"french": "à cet égard", "english": "in this respect", "spanish": "a este respecto", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": False},
    {"french": "en ce qui concerne", "english": "regarding/concerning", "spanish": "en lo que concierne", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": True, "cognate_spanish": "concernir"},
    {"french": "au préalable", "english": "beforehand", "spanish": "previamente", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": False},
    {"french": "en vertu de", "english": "by virtue of", "spanish": "en virtud de", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": True, "cognate_spanish": "virtud"},
    {"french": "en dépit de", "english": "in spite of", "spanish": "a pesar de", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": False},
    {"french": "de surcroît", "english": "moreover", "spanish": "además", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": False},
    {"french": "à l'instar de", "english": "following the example of", "spanish": "a semejanza de", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": False},
    {"french": "d'ores et déjà", "english": "from now on", "spanish": "desde ahora", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": False},
    {"french": "en amont", "english": "upstream/beforehand", "spanish": "aguas arriba", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": False},
    {"french": "en aval", "english": "downstream/afterward", "spanish": "aguas abajo", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": False},
    {"french": "nonobstant", "english": "notwithstanding", "spanish": "no obstante", "gender": "-", "part_of_speech": "preposition", "category": "formal", "is_cognate": True, "cognate_spanish": "obstante"},
    {"french": "eu égard à", "english": "in view of", "spanish": "en consideración a", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": False},
    {"french": "force est de constater", "english": "it must be acknowledged", "spanish": "hay que reconocer", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": False},
    {"french": "il s'avère que", "english": "it turns out that", "spanish": "resulta que", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": False},
    {"french": "il convient de", "english": "it is appropriate to", "spanish": "conviene", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": True, "cognate_spanish": "convenir"},
    {"french": "il incombe à", "english": "it is incumbent upon", "spanish": "incumbe a", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": True, "cognate_spanish": "incumbir"},
    {"french": "en l'espèce", "english": "in this case/matter", "spanish": "en el caso presente", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": True, "cognate_spanish": "especie"},
    {"french": "à fortiori", "english": "all the more so", "spanish": "con mayor razón", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": True, "cognate_spanish": "a fortiori"},
    {"french": "ipso facto", "english": "by the very fact", "spanish": "ipso facto", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": True, "cognate_spanish": "ipso facto"},
    {"french": "a priori", "english": "a priori/at first glance", "spanish": "a priori", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": True, "cognate_spanish": "a priori"},
    {"french": "a posteriori", "english": "a posteriori/in hindsight", "spanish": "a posteriori", "gender": "-", "part_of_speech": "adverb", "category": "formal", "is_cognate": True, "cognate_spanish": "a posteriori"},
    {"french": "sine qua non", "english": "sine qua non/essential", "spanish": "sine qua non", "gender": "-", "part_of_speech": "phrase", "category": "formal", "is_cognate": True, "cognate_spanish": "sine qua non"},

    # Nuanced Emotions (15 items)
    {"french": "l'amertume", "english": "bitterness", "spanish": "la amargura", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "amargura"},
    {"french": "la mélancolie", "english": "melancholy", "spanish": "la melancolía", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "melancolía"},
    {"french": "l'émerveillement", "english": "wonder/amazement", "spanish": "el asombro", "gender": "m", "part_of_speech": "noun", "category": "emotions", "is_cognate": False},
    {"french": "la nostalgie", "english": "nostalgia", "spanish": "la nostalgia", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "nostalgia"},
    {"french": "l'indignation", "english": "indignation", "spanish": "la indignación", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "indignación"},
    {"french": "la résignation", "english": "resignation", "spanish": "la resignación", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "resignación"},
    {"french": "l'exaltation", "english": "exaltation", "spanish": "la exaltación", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "exaltación"},
    {"french": "la stupéfaction", "english": "stupefaction", "spanish": "la estupefacción", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "estupefacción"},
    {"french": "l'effroi", "english": "terror/dread", "spanish": "el pavor", "gender": "m", "part_of_speech": "noun", "category": "emotions", "is_cognate": False},
    {"french": "la lassitude", "english": "weariness", "spanish": "la lasitud", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "lasitud"},
    {"french": "le désarroi", "english": "distress/confusion", "spanish": "el desconcierto", "gender": "m", "part_of_speech": "noun", "category": "emotions", "is_cognate": False},
    {"french": "l'allégresse", "english": "joy/elation", "spanish": "la alegría", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "alegría"},
    {"french": "le dépit", "english": "spite/vexation", "spanish": "el despecho", "gender": "m", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "despecho"},
    {"french": "la perplexité", "english": "perplexity", "spanish": "la perplejidad", "gender": "f", "part_of_speech": "noun", "category": "emotions", "is_cognate": True, "cognate_spanish": "perplejidad"},
    {"french": "l'accablement", "english": "dejection/oppression", "spanish": "el abatimiento", "gender": "m", "part_of_speech": "noun", "category": "emotions", "is_cognate": False},

    # Social Issues (20 items)
    {"french": "l'inégalité", "english": "inequality", "spanish": "la desigualdad", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "desigualdad"},
    {"french": "la précarité", "english": "precariousness/instability", "spanish": "la precariedad", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "precariedad"},
    {"french": "l'exclusion", "english": "exclusion", "spanish": "la exclusión", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "exclusión"},
    {"french": "la solidarité", "english": "solidarity", "spanish": "la solidaridad", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "solidaridad"},
    {"french": "revendiquer", "english": "to claim/demand", "spanish": "reivindicar", "gender": "-", "part_of_speech": "verb", "category": "social", "is_cognate": True, "cognate_spanish": "reivindicar"},
    {"french": "la marginalisation", "english": "marginalization", "spanish": "la marginalización", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "marginalización"},
    {"french": "la stigmatisation", "english": "stigmatization", "spanish": "la estigmatización", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "estigmatización"},
    {"french": "l'ascension sociale", "english": "social mobility", "spanish": "la movilidad social", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "ascensión"},
    {"french": "le déterminisme social", "english": "social determinism", "spanish": "el determinismo social", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "determinismo"},
    {"french": "la stratification", "english": "stratification", "spanish": "la estratificación", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "estratificación"},
    {"french": "le clivage", "english": "divide/cleavage", "spanish": "la división", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": False},
    {"french": "la cohésion", "english": "cohesion", "spanish": "la cohesión", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "cohesión"},
    {"french": "le repli identitaire", "english": "identity withdrawal", "spanish": "el repliegue identitario", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "repliegue"},
    {"french": "le communautarisme", "english": "communitarianism", "spanish": "el comunitarismo", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "comunitarismo"},
    {"french": "l'universalisme", "english": "universalism", "spanish": "el universalismo", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "universalismo"},
    {"french": "le multiculturalisme", "english": "multiculturalism", "spanish": "el multiculturalismo", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "multiculturalismo"},
    {"french": "l'intégration", "english": "integration", "spanish": "la integración", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "integración"},
    {"french": "l'assimilation", "english": "assimilation", "spanish": "la asimilación", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "asimilación"},
    {"french": "le vivre-ensemble", "english": "living together/coexistence", "spanish": "la convivencia", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": False},
    {"french": "le lien social", "english": "social bond", "spanish": "el vínculo social", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "social"},

    # Complex Verbs (25 items)
    {"french": "s'avérer", "english": "to turn out/prove to be", "spanish": "resultar ser", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": False},
    {"french": "se heurter à", "english": "to come up against", "spanish": "chocar con", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": False},
    {"french": "prétendre", "english": "to claim/allege", "spanish": "pretender", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "pretender"},
    {"french": "susciter", "english": "to arouse/provoke", "spanish": "suscitar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "suscitar"},
    {"french": "engendrer", "english": "to engender/cause", "spanish": "engendrar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "engendrar"},
    {"french": "pérenniser", "english": "to perpetuate", "spanish": "perpetuar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "perennizar"},
    {"french": "entériner", "english": "to ratify/endorse", "spanish": "ratificar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": False},
    {"french": "préconiser", "english": "to advocate/recommend", "spanish": "preconizar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "preconizar"},
    {"french": "infirmer", "english": "to invalidate/refute", "spanish": "invalidar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "infirmar"},
    {"french": "étayer", "english": "to support/substantiate", "spanish": "apuntalar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": False},
    {"french": "corroborer", "english": "to corroborate", "spanish": "corroborar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "corroborar"},
    {"french": "stipuler", "english": "to stipulate", "spanish": "estipular", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "estipular"},
    {"french": "pallier", "english": "to alleviate/offset", "spanish": "paliar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "paliar"},
    {"french": "appréhender", "english": "to apprehend/grasp", "spanish": "aprehender", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "aprehender"},
    {"french": "circonscrire", "english": "to circumscribe/limit", "spanish": "circunscribir", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "circunscribir"},
    {"french": "occulter", "english": "to conceal/overshadow", "spanish": "ocultar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "ocultar"},
    {"french": "se prévaloir de", "english": "to take advantage of", "spanish": "prevalerse de", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "prevalerse"},
    {"french": "décrier", "english": "to decry/disparage", "spanish": "desprestigiar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": False},
    {"french": "entraver", "english": "to hinder/impede", "spanish": "obstaculizar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": False},
    {"french": "astreindre", "english": "to compel/oblige", "spanish": "obligar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": False},
    {"french": "exacerber", "english": "to exacerbate", "spanish": "exacerbar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "exacerbar"},
    {"french": "infléchir", "english": "to inflect/change direction", "spanish": "modificar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "inflexionar"},
    {"french": "véhiculer", "english": "to convey/transmit", "spanish": "vehicular", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "vehicular"},
    {"french": "cautionner", "english": "to endorse/guarantee", "spanish": "avalar", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "caucionar"},
    {"french": "émaner de", "english": "to emanate from", "spanish": "emanar de", "gender": "-", "part_of_speech": "verb", "category": "verbs", "is_cognate": True, "cognate_spanish": "emanar"},

    # Media & Communication Advanced (15 items)
    {"french": "la désinformation", "english": "disinformation", "spanish": "la desinformación", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "desinformación"},
    {"french": "le discours", "english": "discourse/speech", "spanish": "el discurso", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "discurso"},
    {"french": "la rhétorique", "english": "rhetoric", "spanish": "la retórica", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "retórica"},
    {"french": "la propagande", "english": "propaganda", "spanish": "la propaganda", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "propaganda"},
    {"french": "la manipulation", "english": "manipulation", "spanish": "la manipulación", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "manipulación"},
    {"french": "le lobbying", "english": "lobbying", "spanish": "el cabildeo", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "lobbying"},
    {"french": "l'éditorial", "english": "editorial", "spanish": "el editorial", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "editorial"},
    {"french": "la chronique", "english": "column/chronicle", "spanish": "la crónica", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "crónica"},
    {"french": "le biais", "english": "bias", "spanish": "el sesgo", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": False},
    {"french": "la partialité", "english": "partiality", "spanish": "la parcialidad", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "parcialidad"},
    {"french": "l'objectivité", "english": "objectivity", "spanish": "la objetividad", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "objetividad"},
    {"french": "la subjectivité", "english": "subjectivity", "spanish": "la subjetividad", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "subjetividad"},
    {"french": "la déontologie", "english": "deontology/ethics", "spanish": "la deontología", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "deontología"},
    {"french": "le quatrième pouvoir", "english": "fourth estate", "spanish": "el cuarto poder", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "cuarto poder"},
    {"french": "le pluralisme", "english": "pluralism", "spanish": "el pluralismo", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "pluralismo"},
]
