"""
B2 Level Vocabulary - Upper Intermediate
Alliance Française B200-B205 equivalent
Expanded content for sustained practice sessions
"""

VOCABULARY_B2 = [
    # Politics & Society (25 items)
    {"french": "le gouvernement", "english": "government", "spanish": "el gobierno", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "gobierno"},
    {"french": "la politique", "english": "politics/policy", "spanish": "la política", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "política"},
    {"french": "le citoyen", "english": "citizen", "spanish": "el ciudadano", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "ciudadano"},
    {"french": "l'élection", "english": "election", "spanish": "la elección", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "elección"},
    {"french": "voter", "english": "to vote", "spanish": "votar", "gender": "-", "part_of_speech": "verb", "category": "politics", "is_cognate": True, "cognate_spanish": "votar"},
    {"french": "le droit", "english": "right/law", "spanish": "el derecho", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": False},
    {"french": "la liberté", "english": "freedom", "spanish": "la libertad", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "libertad"},
    {"french": "l'égalité", "english": "equality", "spanish": "la igualdad", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "igualdad"},
    {"french": "le parti politique", "english": "political party", "spanish": "el partido político", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "partido"},
    {"french": "le député", "english": "member of parliament", "spanish": "el diputado", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "diputado"},
    {"french": "le sénateur", "english": "senator", "spanish": "el senador", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "senador"},
    {"french": "le ministre", "english": "minister", "spanish": "el ministro", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "ministro"},
    {"french": "la démocratie", "english": "democracy", "spanish": "la democracia", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "democracia"},
    {"french": "la dictature", "english": "dictatorship", "spanish": "la dictadura", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "dictadura"},
    {"french": "le scrutin", "english": "ballot/vote", "spanish": "el escrutinio", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "escrutinio"},
    {"french": "la campagne", "english": "campaign", "spanish": "la campaña", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "campaña"},
    {"french": "le candidat", "english": "candidate", "spanish": "el candidato", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "candidato"},
    {"french": "le référendum", "english": "referendum", "spanish": "el referéndum", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "referéndum"},
    {"french": "la réforme", "english": "reform", "spanish": "la reforma", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "reforma"},
    {"french": "la constitution", "english": "constitution", "spanish": "la constitución", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "constitución"},
    {"french": "promulguer", "english": "to enact/promulgate", "spanish": "promulgar", "gender": "-", "part_of_speech": "verb", "category": "politics", "is_cognate": True, "cognate_spanish": "promulgar"},
    {"french": "légiférer", "english": "to legislate", "spanish": "legislar", "gender": "-", "part_of_speech": "verb", "category": "politics", "is_cognate": True, "cognate_spanish": "legislar"},
    {"french": "le mandat", "english": "mandate/term", "spanish": "el mandato", "gender": "m", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "mandato"},
    {"french": "l'opposition", "english": "opposition", "spanish": "la oposición", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "oposición"},
    {"french": "la majorité", "english": "majority", "spanish": "la mayoría", "gender": "f", "part_of_speech": "noun", "category": "politics", "is_cognate": True, "cognate_spanish": "mayoría"},

    # Economy & Finance (25 items)
    {"french": "l'économie", "english": "economy", "spanish": "la economía", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "economía"},
    {"french": "le marché", "english": "market", "spanish": "el mercado", "gender": "m", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "mercado"},
    {"french": "l'investissement", "english": "investment", "spanish": "la inversión", "gender": "m", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "inversión"},
    {"french": "le chômage", "english": "unemployment", "spanish": "el desempleo", "gender": "m", "part_of_speech": "noun", "category": "economy", "is_cognate": False},
    {"french": "la croissance", "english": "growth", "spanish": "el crecimiento", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": False},
    {"french": "emprunter", "english": "to borrow", "spanish": "pedir prestado", "gender": "-", "part_of_speech": "verb", "category": "economy", "is_cognate": False},
    {"french": "épargner", "english": "to save (money)", "spanish": "ahorrar", "gender": "-", "part_of_speech": "verb", "category": "economy", "is_cognate": False},
    {"french": "l'inflation", "english": "inflation", "spanish": "la inflación", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "inflación"},
    {"french": "la récession", "english": "recession", "spanish": "la recesión", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "recesión"},
    {"french": "le PIB", "english": "GDP", "spanish": "el PIB", "gender": "m", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "PIB"},
    {"french": "la dette", "english": "debt", "spanish": "la deuda", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": False},
    {"french": "le budget", "english": "budget", "spanish": "el presupuesto", "gender": "m", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "budget"},
    {"french": "l'impôt", "english": "tax", "spanish": "el impuesto", "gender": "m", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "impuesto"},
    {"french": "la bourse", "english": "stock market", "spanish": "la bolsa", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "bolsa"},
    {"french": "l'action", "english": "stock/share", "spanish": "la acción", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "acción"},
    {"french": "le taux d'intérêt", "english": "interest rate", "spanish": "la tasa de interés", "gender": "m", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "tasa"},
    {"french": "la devise", "english": "currency", "spanish": "la divisa", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "divisa"},
    {"french": "le commerce", "english": "trade/commerce", "spanish": "el comercio", "gender": "m", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "comercio"},
    {"french": "l'exportation", "english": "export", "spanish": "la exportación", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "exportación"},
    {"french": "l'importation", "english": "import", "spanish": "la importación", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "importación"},
    {"french": "la concurrence", "english": "competition", "spanish": "la competencia", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "concurrencia"},
    {"french": "le bénéfice", "english": "profit", "spanish": "el beneficio", "gender": "m", "part_of_speech": "noun", "category": "economy", "is_cognate": True, "cognate_spanish": "beneficio"},
    {"french": "la perte", "english": "loss", "spanish": "la pérdida", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": False},
    {"french": "rentable", "english": "profitable", "spanish": "rentable", "gender": "-", "part_of_speech": "adjective", "category": "economy", "is_cognate": True, "cognate_spanish": "rentable"},
    {"french": "la faillite", "english": "bankruptcy", "spanish": "la quiebra", "gender": "f", "part_of_speech": "noun", "category": "economy", "is_cognate": False},

    # Science & Research (20 items)
    {"french": "la recherche", "english": "research", "spanish": "la investigación", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": False},
    {"french": "le scientifique", "english": "scientist", "spanish": "el científico", "gender": "m", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "científico"},
    {"french": "découvrir", "english": "to discover", "spanish": "descubrir", "gender": "-", "part_of_speech": "verb", "category": "science", "is_cognate": True, "cognate_spanish": "descubrir"},
    {"french": "l'expérience", "english": "experiment/experience", "spanish": "el experimento/la experiencia", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "experiencia"},
    {"french": "prouver", "english": "to prove", "spanish": "probar", "gender": "-", "part_of_speech": "verb", "category": "science", "is_cognate": True, "cognate_spanish": "probar"},
    {"french": "le résultat", "english": "result", "spanish": "el resultado", "gender": "m", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "resultado"},
    {"french": "l'hypothèse", "english": "hypothesis", "spanish": "la hipótesis", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "hipótesis"},
    {"french": "la théorie", "english": "theory", "spanish": "la teoría", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "teoría"},
    {"french": "le laboratoire", "english": "laboratory", "spanish": "el laboratorio", "gender": "m", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "laboratorio"},
    {"french": "l'analyse", "english": "analysis", "spanish": "el análisis", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "análisis"},
    {"french": "la donnée", "english": "data", "spanish": "el dato", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": False},
    {"french": "la méthode", "english": "method", "spanish": "el método", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "método"},
    {"french": "l'étude", "english": "study", "spanish": "el estudio", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "estudio"},
    {"french": "la conclusion", "english": "conclusion", "spanish": "la conclusión", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "conclusión"},
    {"french": "l'observation", "english": "observation", "spanish": "la observación", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "observación"},
    {"french": "démontrer", "english": "to demonstrate", "spanish": "demostrar", "gender": "-", "part_of_speech": "verb", "category": "science", "is_cognate": True, "cognate_spanish": "demostrar"},
    {"french": "valider", "english": "to validate", "spanish": "validar", "gender": "-", "part_of_speech": "verb", "category": "science", "is_cognate": True, "cognate_spanish": "validar"},
    {"french": "la variable", "english": "variable", "spanish": "la variable", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "variable"},
    {"french": "l'échantillon", "english": "sample", "spanish": "la muestra", "gender": "m", "part_of_speech": "noun", "category": "science", "is_cognate": False},
    {"french": "la statistique", "english": "statistic", "spanish": "la estadística", "gender": "f", "part_of_speech": "noun", "category": "science", "is_cognate": True, "cognate_spanish": "estadística"},

    # Arts & Culture (20 items)
    {"french": "l'œuvre", "english": "work (of art)", "spanish": "la obra", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "obra"},
    {"french": "le patrimoine", "english": "heritage", "spanish": "el patrimonio", "gender": "m", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "patrimonio"},
    {"french": "la peinture", "english": "painting", "spanish": "la pintura", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "pintura"},
    {"french": "le spectacle", "english": "show/performance", "spanish": "el espectáculo", "gender": "m", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "espectáculo"},
    {"french": "interpréter", "english": "to perform/interpret", "spanish": "interpretar", "gender": "-", "part_of_speech": "verb", "category": "arts", "is_cognate": True, "cognate_spanish": "interpretar"},
    {"french": "la sculpture", "english": "sculpture", "spanish": "la escultura", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "escultura"},
    {"french": "l'exposition", "english": "exhibition", "spanish": "la exposición", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "exposición"},
    {"french": "le musée", "english": "museum", "spanish": "el museo", "gender": "m", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "museo"},
    {"french": "l'artiste", "english": "artist", "spanish": "el artista", "gender": "m", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "artista"},
    {"french": "le chef-d'œuvre", "english": "masterpiece", "spanish": "la obra maestra", "gender": "m", "part_of_speech": "noun", "category": "arts", "is_cognate": False},
    {"french": "la galerie", "english": "gallery", "spanish": "la galería", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "galería"},
    {"french": "le mouvement", "english": "movement", "spanish": "el movimiento", "gender": "m", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "movimiento"},
    {"french": "l'époque", "english": "era/period", "spanish": "la época", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "época"},
    {"french": "le style", "english": "style", "spanish": "el estilo", "gender": "m", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "estilo"},
    {"french": "l'architecture", "english": "architecture", "spanish": "la arquitectura", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "arquitectura"},
    {"french": "la littérature", "english": "literature", "spanish": "la literatura", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "literatura"},
    {"french": "le roman", "english": "novel", "spanish": "la novela", "gender": "m", "part_of_speech": "noun", "category": "arts", "is_cognate": False},
    {"french": "la poésie", "english": "poetry", "spanish": "la poesía", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "poesía"},
    {"french": "le metteur en scène", "english": "director", "spanish": "el director", "gender": "m", "part_of_speech": "noun", "category": "arts", "is_cognate": False},
    {"french": "la critique", "english": "criticism/review", "spanish": "la crítica", "gender": "f", "part_of_speech": "noun", "category": "arts", "is_cognate": True, "cognate_spanish": "crítica"},

    # Abstract Concepts (20 items)
    {"french": "la conscience", "english": "consciousness/awareness", "spanish": "la conciencia", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "conciencia"},
    {"french": "l'influence", "english": "influence", "spanish": "la influencia", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "influencia"},
    {"french": "le comportement", "english": "behavior", "spanish": "el comportamiento", "gender": "m", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "comportamiento"},
    {"french": "l'attitude", "english": "attitude", "spanish": "la actitud", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "actitud"},
    {"french": "la tendance", "english": "trend/tendency", "spanish": "la tendencia", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "tendencia"},
    {"french": "constater", "english": "to notice/observe", "spanish": "constatar", "gender": "-", "part_of_speech": "verb", "category": "abstract", "is_cognate": True, "cognate_spanish": "constatar"},
    {"french": "le concept", "english": "concept", "spanish": "el concepto", "gender": "m", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "concepto"},
    {"french": "la perception", "english": "perception", "spanish": "la percepción", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "percepción"},
    {"french": "la réalité", "english": "reality", "spanish": "la realidad", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "realidad"},
    {"french": "l'apparence", "english": "appearance", "spanish": "la apariencia", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "apariencia"},
    {"french": "l'identité", "english": "identity", "spanish": "la identidad", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "identidad"},
    {"french": "la valeur", "english": "value", "spanish": "el valor", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "valor"},
    {"french": "le principe", "english": "principle", "spanish": "el principio", "gender": "m", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "principio"},
    {"french": "la norme", "english": "norm/standard", "spanish": "la norma", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "norma"},
    {"french": "l'éthique", "english": "ethics", "spanish": "la ética", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "ética"},
    {"french": "la morale", "english": "morality", "spanish": "la moral", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "moral"},
    {"french": "le paradoxe", "english": "paradox", "spanish": "la paradoja", "gender": "m", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "paradoja"},
    {"french": "la complexité", "english": "complexity", "spanish": "la complejidad", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "complejidad"},
    {"french": "la nuance", "english": "nuance", "spanish": "el matiz", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "nuance"},
    {"french": "l'ambiguïté", "english": "ambiguity", "spanish": "la ambigüedad", "gender": "f", "part_of_speech": "noun", "category": "abstract", "is_cognate": True, "cognate_spanish": "ambigüedad"},

    # Legal & Administrative (20 items)
    {"french": "la loi", "english": "law", "spanish": "la ley", "gender": "f", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "ley"},
    {"french": "le tribunal", "english": "court", "spanish": "el tribunal", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "tribunal"},
    {"french": "l'avocat", "english": "lawyer", "spanish": "el abogado", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "abogado"},
    {"french": "juger", "english": "to judge", "spanish": "juzgar", "gender": "-", "part_of_speech": "verb", "category": "legal", "is_cognate": True, "cognate_spanish": "juzgar"},
    {"french": "le témoin", "english": "witness", "spanish": "el testigo", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": False},
    {"french": "la preuve", "english": "proof/evidence", "spanish": "la prueba", "gender": "f", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "prueba"},
    {"french": "le procès", "english": "trial", "spanish": "el proceso", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "proceso"},
    {"french": "l'accusé", "english": "defendant", "spanish": "el acusado", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "acusado"},
    {"french": "la victime", "english": "victim", "spanish": "la víctima", "gender": "f", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "víctima"},
    {"french": "le crime", "english": "crime", "spanish": "el crimen", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "crimen"},
    {"french": "le délit", "english": "offense/misdemeanor", "spanish": "el delito", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "delito"},
    {"french": "la condamnation", "english": "conviction/sentence", "spanish": "la condena", "gender": "f", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "condena"},
    {"french": "l'amende", "english": "fine", "spanish": "la multa", "gender": "f", "part_of_speech": "noun", "category": "legal", "is_cognate": False},
    {"french": "la prison", "english": "prison", "spanish": "la prisión", "gender": "f", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "prisión"},
    {"french": "innocent", "english": "innocent", "spanish": "inocente", "gender": "m", "part_of_speech": "adjective", "category": "legal", "is_cognate": True, "cognate_spanish": "inocente"},
    {"french": "coupable", "english": "guilty", "spanish": "culpable", "gender": "-", "part_of_speech": "adjective", "category": "legal", "is_cognate": True, "cognate_spanish": "culpable"},
    {"french": "le juge", "english": "judge", "spanish": "el juez", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "juez"},
    {"french": "le jury", "english": "jury", "spanish": "el jurado", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "jurado"},
    {"french": "acquitter", "english": "to acquit", "spanish": "absolver", "gender": "-", "part_of_speech": "verb", "category": "legal", "is_cognate": False},
    {"french": "le verdict", "english": "verdict", "spanish": "el veredicto", "gender": "m", "part_of_speech": "noun", "category": "legal", "is_cognate": True, "cognate_spanish": "veredicto"},

    # Connectors & Discourse (25 items)
    {"french": "cependant", "english": "however", "spanish": "sin embargo", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "néanmoins", "english": "nevertheless", "spanish": "no obstante", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "d'ailleurs", "english": "besides/moreover", "spanish": "además", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "en revanche", "english": "on the other hand", "spanish": "en cambio", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "ainsi", "english": "thus/therefore", "spanish": "así", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": True, "cognate_spanish": "así"},
    {"french": "par conséquent", "english": "consequently", "spanish": "por consiguiente", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": True, "cognate_spanish": "consecuente"},
    {"french": "toutefois", "english": "however/yet", "spanish": "sin embargo", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "en effet", "english": "indeed/in fact", "spanish": "en efecto", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": True, "cognate_spanish": "en efecto"},
    {"french": "autrement dit", "english": "in other words", "spanish": "es decir", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "c'est-à-dire", "english": "that is to say", "spanish": "es decir", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "en outre", "english": "furthermore", "spanish": "además", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "de plus", "english": "moreover", "spanish": "además", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "par ailleurs", "english": "furthermore/besides", "spanish": "por otra parte", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": False},
    {"french": "en somme", "english": "in short", "spanish": "en resumen", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": True, "cognate_spanish": "suma"},
    {"french": "bref", "english": "in brief", "spanish": "en breve", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": True, "cognate_spanish": "breve"},
    {"french": "certes", "english": "certainly/admittedly", "spanish": "ciertamente", "gender": "-", "part_of_speech": "adverb", "category": "discourse", "is_cognate": True, "cognate_spanish": "cierto"},
    {"french": "or", "english": "now/yet", "spanish": "ahora bien", "gender": "-", "part_of_speech": "conjunction", "category": "discourse", "is_cognate": False},
    {"french": "quant à", "english": "as for", "spanish": "en cuanto a", "gender": "-", "part_of_speech": "preposition", "category": "discourse", "is_cognate": True, "cognate_spanish": "cuanto"},
    {"french": "en ce qui concerne", "english": "regarding/concerning", "spanish": "en lo que concierne", "gender": "-", "part_of_speech": "phrase", "category": "discourse", "is_cognate": True, "cognate_spanish": "concernir"},
    {"french": "à cet égard", "english": "in this respect", "spanish": "a este respecto", "gender": "-", "part_of_speech": "phrase", "category": "discourse", "is_cognate": False},
    {"french": "étant donné que", "english": "given that", "spanish": "dado que", "gender": "-", "part_of_speech": "phrase", "category": "discourse", "is_cognate": False},
    {"french": "à condition que", "english": "provided that", "spanish": "con la condición de que", "gender": "-", "part_of_speech": "phrase", "category": "discourse", "is_cognate": True, "cognate_spanish": "condición"},
    {"french": "bien que", "english": "although", "spanish": "aunque", "gender": "-", "part_of_speech": "conjunction", "category": "discourse", "is_cognate": False},
    {"french": "malgré", "english": "despite", "spanish": "a pesar de", "gender": "-", "part_of_speech": "preposition", "category": "discourse", "is_cognate": False},
    {"french": "afin de", "english": "in order to", "spanish": "con el fin de", "gender": "-", "part_of_speech": "phrase", "category": "discourse", "is_cognate": False},

    # Psychology & Behavior (15 items)
    {"french": "le caractère", "english": "character/temperament", "spanish": "el carácter", "gender": "m", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "carácter"},
    {"french": "la personnalité", "english": "personality", "spanish": "la personalidad", "gender": "f", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "personalidad"},
    {"french": "l'émotion", "english": "emotion", "spanish": "la emoción", "gender": "f", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "emoción"},
    {"french": "le sentiment", "english": "feeling", "spanish": "el sentimiento", "gender": "m", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "sentimiento"},
    {"french": "l'intuition", "english": "intuition", "spanish": "la intuición", "gender": "f", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "intuición"},
    {"french": "la mémoire", "english": "memory", "spanish": "la memoria", "gender": "f", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "memoria"},
    {"french": "l'inconscient", "english": "unconscious", "spanish": "el inconsciente", "gender": "m", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "inconsciente"},
    {"french": "le traumatisme", "english": "trauma", "spanish": "el trauma", "gender": "m", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "trauma"},
    {"french": "l'anxiété", "english": "anxiety", "spanish": "la ansiedad", "gender": "f", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "ansiedad"},
    {"french": "la dépression", "english": "depression", "spanish": "la depresión", "gender": "f", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "depresión"},
    {"french": "le stress", "english": "stress", "spanish": "el estrés", "gender": "m", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "estrés"},
    {"french": "le bien-être", "english": "well-being", "spanish": "el bienestar", "gender": "m", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "bienestar"},
    {"french": "la résilience", "english": "resilience", "spanish": "la resiliencia", "gender": "f", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "resiliencia"},
    {"french": "l'empathie", "english": "empathy", "spanish": "la empatía", "gender": "f", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "empatía"},
    {"french": "le subconscient", "english": "subconscious", "spanish": "el subconsciente", "gender": "m", "part_of_speech": "noun", "category": "psychology", "is_cognate": True, "cognate_spanish": "subconsciente"},
]
