"""
B1 Level Vocabulary - Intermediate
Alliance Française B100-B105 equivalent
Expanded content for sustained practice sessions
"""

VOCABULARY_B1 = [
    # Work & Career (25 items)
    {"french": "le travail", "english": "work/job", "spanish": "el trabajo", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "trabajo"},
    {"french": "l'entreprise", "english": "company/business", "spanish": "la empresa", "gender": "f", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "empresa"},
    {"french": "le bureau", "english": "office/desk", "spanish": "la oficina/el escritorio", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": False},
    {"french": "le collègue", "english": "colleague", "spanish": "el colega", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "colega"},
    {"french": "le patron", "english": "boss", "spanish": "el jefe/patrón", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "patrón"},
    {"french": "le salaire", "english": "salary", "spanish": "el salario", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "salario"},
    {"french": "embaucher", "english": "to hire", "spanish": "contratar", "gender": "-", "part_of_speech": "verb", "category": "work", "is_cognate": False},
    {"french": "licencier", "english": "to fire/lay off", "spanish": "despedir", "gender": "-", "part_of_speech": "verb", "category": "work", "is_cognate": False},
    {"french": "la réunion", "english": "meeting", "spanish": "la reunión", "gender": "f", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "reunión"},
    {"french": "le métier", "english": "profession/trade", "spanish": "el oficio", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": False},
    {"french": "la carrière", "english": "career", "spanish": "la carrera", "gender": "f", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "carrera"},
    {"french": "le contrat", "english": "contract", "spanish": "el contrato", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "contrato"},
    {"french": "le CV", "english": "resume/CV", "spanish": "el currículum", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "currículum"},
    {"french": "l'entretien", "english": "interview", "spanish": "la entrevista", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": False},
    {"french": "postuler", "english": "to apply (for job)", "spanish": "postular", "gender": "-", "part_of_speech": "verb", "category": "work", "is_cognate": True, "cognate_spanish": "postular"},
    {"french": "démissionner", "english": "to resign", "spanish": "dimitir", "gender": "-", "part_of_speech": "verb", "category": "work", "is_cognate": True, "cognate_spanish": "dimitir"},
    {"french": "le chômage", "english": "unemployment", "spanish": "el desempleo", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": False},
    {"french": "la promotion", "english": "promotion", "spanish": "la promoción", "gender": "f", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "promoción"},
    {"french": "le stage", "english": "internship", "spanish": "la práctica", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": False},
    {"french": "le stagiaire", "english": "intern", "spanish": "el practicante", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": False},
    {"french": "l'employé", "english": "employee", "spanish": "el empleado", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "empleado"},
    {"french": "l'employeur", "english": "employer", "spanish": "el empleador", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "empleador"},
    {"french": "le congé", "english": "leave/holiday", "spanish": "la licencia", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": False},
    {"french": "les heures supplémentaires", "english": "overtime", "spanish": "las horas extras", "gender": "f", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "suplementarias"},
    {"french": "le télétravail", "english": "remote work", "spanish": "el teletrabajo", "gender": "m", "part_of_speech": "noun", "category": "work", "is_cognate": True, "cognate_spanish": "teletrabajo"},

    # Education (20 items)
    {"french": "l'université", "english": "university", "spanish": "la universidad", "gender": "f", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "universidad"},
    {"french": "le diplôme", "english": "diploma/degree", "spanish": "el diploma", "gender": "m", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "diploma"},
    {"french": "la formation", "english": "training/education", "spanish": "la formación", "gender": "f", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "formación"},
    {"french": "réussir", "english": "to succeed/pass", "spanish": "aprobar/tener éxito", "gender": "-", "part_of_speech": "verb", "category": "education", "is_cognate": False},
    {"french": "échouer", "english": "to fail", "spanish": "fracasar/suspender", "gender": "-", "part_of_speech": "verb", "category": "education", "is_cognate": False},
    {"french": "la licence", "english": "bachelor's degree", "spanish": "la licenciatura", "gender": "f", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "licenciatura"},
    {"french": "le master", "english": "master's degree", "spanish": "la maestría", "gender": "m", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "máster"},
    {"french": "le doctorat", "english": "doctorate", "spanish": "el doctorado", "gender": "m", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "doctorado"},
    {"french": "la bourse", "english": "scholarship", "spanish": "la beca", "gender": "f", "part_of_speech": "noun", "category": "education", "is_cognate": False},
    {"french": "le cours", "english": "course/class", "spanish": "el curso", "gender": "m", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "curso"},
    {"french": "le séminaire", "english": "seminar", "spanish": "el seminario", "gender": "m", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "seminario"},
    {"french": "la conférence", "english": "lecture/conference", "spanish": "la conferencia", "gender": "f", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "conferencia"},
    {"french": "le mémoire", "english": "thesis/dissertation", "spanish": "la tesis", "gender": "m", "part_of_speech": "noun", "category": "education", "is_cognate": False},
    {"french": "la recherche", "english": "research", "spanish": "la investigación", "gender": "f", "part_of_speech": "noun", "category": "education", "is_cognate": False},
    {"french": "le professeur", "english": "professor", "spanish": "el profesor", "gender": "m", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "profesor"},
    {"french": "l'étudiant", "english": "student", "spanish": "el estudiante", "gender": "m", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "estudiante"},
    {"french": "s'inscrire", "english": "to enroll", "spanish": "inscribirse", "gender": "-", "part_of_speech": "verb", "category": "education", "is_cognate": True, "cognate_spanish": "inscribirse"},
    {"french": "la faculté", "english": "faculty", "spanish": "la facultad", "gender": "f", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "facultad"},
    {"french": "la spécialisation", "english": "specialization", "spanish": "la especialización", "gender": "f", "part_of_speech": "noun", "category": "education", "is_cognate": True, "cognate_spanish": "especialización"},
    {"french": "approfondir", "english": "to deepen/study in depth", "spanish": "profundizar", "gender": "-", "part_of_speech": "verb", "category": "education", "is_cognate": True, "cognate_spanish": "profundizar"},

    # Environment & Nature (20 items)
    {"french": "l'environnement", "english": "environment", "spanish": "el medio ambiente", "gender": "m", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "ambiente"},
    {"french": "la pollution", "english": "pollution", "spanish": "la contaminación", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "polución"},
    {"french": "recycler", "english": "to recycle", "spanish": "reciclar", "gender": "-", "part_of_speech": "verb", "category": "environment", "is_cognate": True, "cognate_spanish": "reciclar"},
    {"french": "la forêt", "english": "forest", "spanish": "el bosque", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": False},
    {"french": "la montagne", "english": "mountain", "spanish": "la montaña", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "montaña"},
    {"french": "la mer", "english": "sea", "spanish": "el mar", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "mar"},
    {"french": "le réchauffement climatique", "english": "global warming", "spanish": "el calentamiento global", "gender": "m", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "climático"},
    {"french": "l'énergie renouvelable", "english": "renewable energy", "spanish": "la energía renovable", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "renovable"},
    {"french": "le développement durable", "english": "sustainable development", "spanish": "el desarrollo sostenible", "gender": "m", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "desarrollo"},
    {"french": "la biodiversité", "english": "biodiversity", "spanish": "la biodiversidad", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "biodiversidad"},
    {"french": "le déchet", "english": "waste/trash", "spanish": "el residuo", "gender": "m", "part_of_speech": "noun", "category": "environment", "is_cognate": False},
    {"french": "la protection", "english": "protection", "spanish": "la protección", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "protección"},
    {"french": "préserver", "english": "to preserve", "spanish": "preservar", "gender": "-", "part_of_speech": "verb", "category": "environment", "is_cognate": True, "cognate_spanish": "preservar"},
    {"french": "la nature", "english": "nature", "spanish": "la naturaleza", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "naturaleza"},
    {"french": "l'écologie", "english": "ecology", "spanish": "la ecología", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "ecología"},
    {"french": "le climat", "english": "climate", "spanish": "el clima", "gender": "m", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "clima"},
    {"french": "l'espèce", "english": "species", "spanish": "la especie", "gender": "f", "part_of_speech": "noun", "category": "environment", "is_cognate": True, "cognate_spanish": "especie"},
    {"french": "menacé", "english": "threatened", "spanish": "amenazado", "gender": "m", "part_of_speech": "adjective", "category": "environment", "is_cognate": True, "cognate_spanish": "amenazado"},
    {"french": "durable", "english": "sustainable", "spanish": "sostenible", "gender": "-", "part_of_speech": "adjective", "category": "environment", "is_cognate": True, "cognate_spanish": "durable"},
    {"french": "polluer", "english": "to pollute", "spanish": "contaminar", "gender": "-", "part_of_speech": "verb", "category": "environment", "is_cognate": True, "cognate_spanish": "polucionar"},

    # Technology (20 items)
    {"french": "l'ordinateur", "english": "computer", "spanish": "el ordenador", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": True, "cognate_spanish": "ordenador"},
    {"french": "le logiciel", "english": "software", "spanish": "el software/programa", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": False},
    {"french": "télécharger", "english": "to download", "spanish": "descargar", "gender": "-", "part_of_speech": "verb", "category": "technology", "is_cognate": False},
    {"french": "le réseau", "english": "network", "spanish": "la red", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": False},
    {"french": "le mot de passe", "english": "password", "spanish": "la contraseña", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": False},
    {"french": "l'application", "english": "application/app", "spanish": "la aplicación", "gender": "f", "part_of_speech": "noun", "category": "technology", "is_cognate": True, "cognate_spanish": "aplicación"},
    {"french": "le navigateur", "english": "browser", "spanish": "el navegador", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": True, "cognate_spanish": "navegador"},
    {"french": "le site web", "english": "website", "spanish": "el sitio web", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": True, "cognate_spanish": "sitio"},
    {"french": "le fichier", "english": "file", "spanish": "el archivo", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": False},
    {"french": "sauvegarder", "english": "to save", "spanish": "guardar", "gender": "-", "part_of_speech": "verb", "category": "technology", "is_cognate": False},
    {"french": "supprimer", "english": "to delete", "spanish": "eliminar", "gender": "-", "part_of_speech": "verb", "category": "technology", "is_cognate": True, "cognate_spanish": "suprimir"},
    {"french": "le clavier", "english": "keyboard", "spanish": "el teclado", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": False},
    {"french": "la souris", "english": "mouse", "spanish": "el ratón", "gender": "f", "part_of_speech": "noun", "category": "technology", "is_cognate": False},
    {"french": "l'écran", "english": "screen", "spanish": "la pantalla", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": False},
    {"french": "imprimer", "english": "to print", "spanish": "imprimir", "gender": "-", "part_of_speech": "verb", "category": "technology", "is_cognate": True, "cognate_spanish": "imprimir"},
    {"french": "l'imprimante", "english": "printer", "spanish": "la impresora", "gender": "f", "part_of_speech": "noun", "category": "technology", "is_cognate": True, "cognate_spanish": "impresora"},
    {"french": "le disque dur", "english": "hard drive", "spanish": "el disco duro", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": True, "cognate_spanish": "disco"},
    {"french": "la connexion", "english": "connection", "spanish": "la conexión", "gender": "f", "part_of_speech": "noun", "category": "technology", "is_cognate": True, "cognate_spanish": "conexión"},
    {"french": "le bug", "english": "bug/glitch", "spanish": "el error", "gender": "m", "part_of_speech": "noun", "category": "technology", "is_cognate": False},
    {"french": "mettre à jour", "english": "to update", "spanish": "actualizar", "gender": "-", "part_of_speech": "verb", "category": "technology", "is_cognate": False},

    # Emotions & Feelings (20 items)
    {"french": "heureux", "english": "happy", "spanish": "feliz", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "triste", "english": "sad", "spanish": "triste", "gender": "-", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "triste"},
    {"french": "inquiet", "english": "worried", "spanish": "preocupado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "fier", "english": "proud", "spanish": "orgulloso", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "déçu", "english": "disappointed", "spanish": "decepcionado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "decepcionado"},
    {"french": "surpris", "english": "surprised", "spanish": "sorprendido", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "sorprendido"},
    {"french": "soulagé", "english": "relieved", "spanish": "aliviado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "frustré", "english": "frustrated", "spanish": "frustrado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "frustrado"},
    {"french": "confus", "english": "confused", "spanish": "confundido", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "confuso"},
    {"french": "enthousiaste", "english": "enthusiastic", "spanish": "entusiasmado", "gender": "-", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "entusiasta"},
    {"french": "reconnaissant", "english": "grateful", "spanish": "agradecido", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "gêné", "english": "embarrassed", "spanish": "avergonzado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "nostalgique", "english": "nostalgic", "spanish": "nostálgico", "gender": "-", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "nostálgico"},
    {"french": "optimiste", "english": "optimistic", "spanish": "optimista", "gender": "-", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "optimista"},
    {"french": "pessimiste", "english": "pessimistic", "spanish": "pesimista", "gender": "-", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "pesimista"},
    {"french": "satisfait", "english": "satisfied", "spanish": "satisfecho", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "satisfecho"},
    {"french": "stressé", "english": "stressed", "spanish": "estresado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "estresado"},
    {"french": "épuisé", "english": "exhausted", "spanish": "agotado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "motivé", "english": "motivated", "spanish": "motivado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "motivado"},
    {"french": "indifférent", "english": "indifferent", "spanish": "indiferente", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "indiferente"},

    # Media & Communication (20 items)
    {"french": "le journal", "english": "newspaper", "spanish": "el periódico", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": False},
    {"french": "les informations", "english": "news", "spanish": "las noticias", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "información"},
    {"french": "la publicité", "english": "advertisement", "spanish": "la publicidad", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "publicidad"},
    {"french": "diffuser", "english": "to broadcast", "spanish": "difundir", "gender": "-", "part_of_speech": "verb", "category": "media", "is_cognate": True, "cognate_spanish": "difundir"},
    {"french": "la chaîne", "english": "channel", "spanish": "el canal", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": False},
    {"french": "l'émission", "english": "program/show", "spanish": "el programa", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "emisión"},
    {"french": "le documentaire", "english": "documentary", "spanish": "el documental", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "documental"},
    {"french": "le reportage", "english": "report/coverage", "spanish": "el reportaje", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "reportaje"},
    {"french": "le journaliste", "english": "journalist", "spanish": "el periodista", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "periodista"},
    {"french": "la presse", "english": "press/media", "spanish": "la prensa", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "prensa"},
    {"french": "l'article", "english": "article", "spanish": "el artículo", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "artículo"},
    {"french": "la rubrique", "english": "section/column", "spanish": "la sección", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "rúbrica"},
    {"french": "le titre", "english": "headline/title", "spanish": "el titular", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "título"},
    {"french": "l'interview", "english": "interview", "spanish": "la entrevista", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "entrevista"},
    {"french": "le réseau social", "english": "social network", "spanish": "la red social", "gender": "m", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "red social"},
    {"french": "publier", "english": "to publish", "spanish": "publicar", "gender": "-", "part_of_speech": "verb", "category": "media", "is_cognate": True, "cognate_spanish": "publicar"},
    {"french": "partager", "english": "to share", "spanish": "compartir", "gender": "-", "part_of_speech": "verb", "category": "media", "is_cognate": False},
    {"french": "commenter", "english": "to comment", "spanish": "comentar", "gender": "-", "part_of_speech": "verb", "category": "media", "is_cognate": True, "cognate_spanish": "comentar"},
    {"french": "s'abonner", "english": "to subscribe", "spanish": "suscribirse", "gender": "-", "part_of_speech": "verb", "category": "media", "is_cognate": True, "cognate_spanish": "abonarse"},
    {"french": "l'actualité", "english": "current events", "spanish": "la actualidad", "gender": "f", "part_of_speech": "noun", "category": "media", "is_cognate": True, "cognate_spanish": "actualidad"},

    # Health & Medicine (20 items)
    {"french": "la maladie", "english": "illness/disease", "spanish": "la enfermedad", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "le symptôme", "english": "symptom", "spanish": "el síntoma", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "síntoma"},
    {"french": "le traitement", "english": "treatment", "spanish": "el tratamiento", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "tratamiento"},
    {"french": "soigner", "english": "to treat/care for", "spanish": "tratar/cuidar", "gender": "-", "part_of_speech": "verb", "category": "health", "is_cognate": False},
    {"french": "guérir", "english": "to heal/cure", "spanish": "curar", "gender": "-", "part_of_speech": "verb", "category": "health", "is_cognate": False},
    {"french": "l'hôpital", "english": "hospital", "spanish": "el hospital", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "hospital"},
    {"french": "la clinique", "english": "clinic", "spanish": "la clínica", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "clínica"},
    {"french": "l'infirmier", "english": "nurse", "spanish": "el enfermero", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "enfermero"},
    {"french": "le chirurgien", "english": "surgeon", "spanish": "el cirujano", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "cirujano"},
    {"french": "l'opération", "english": "operation/surgery", "spanish": "la operación", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "operación"},
    {"french": "le vaccin", "english": "vaccine", "spanish": "la vacuna", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "vacuna"},
    {"french": "la piqûre", "english": "injection/shot", "spanish": "la inyección", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "le rendez-vous", "english": "appointment", "spanish": "la cita", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "l'urgence", "english": "emergency", "spanish": "la urgencia", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "urgencia"},
    {"french": "la douleur", "english": "pain", "spanish": "el dolor", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "dolor"},
    {"french": "chronique", "english": "chronic", "spanish": "crónico", "gender": "-", "part_of_speech": "adjective", "category": "health", "is_cognate": True, "cognate_spanish": "crónico"},
    {"french": "contagieux", "english": "contagious", "spanish": "contagioso", "gender": "m", "part_of_speech": "adjective", "category": "health", "is_cognate": True, "cognate_spanish": "contagioso"},
    {"french": "le diagnostic", "english": "diagnosis", "spanish": "el diagnóstico", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "diagnóstico"},
    {"french": "prescrire", "english": "to prescribe", "spanish": "recetar", "gender": "-", "part_of_speech": "verb", "category": "health", "is_cognate": True, "cognate_spanish": "prescribir"},
    {"french": "la consultation", "english": "consultation", "spanish": "la consulta", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "consulta"},

    # Travel & Tourism (20 items)
    {"french": "le tourisme", "english": "tourism", "spanish": "el turismo", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "turismo"},
    {"french": "le touriste", "english": "tourist", "spanish": "el turista", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "turista"},
    {"french": "la destination", "english": "destination", "spanish": "el destino", "gender": "f", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "destino"},
    {"french": "le vol", "english": "flight", "spanish": "el vuelo", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": False},
    {"french": "la réservation", "english": "reservation/booking", "spanish": "la reserva", "gender": "f", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "reservación"},
    {"french": "l'hôtel", "english": "hotel", "spanish": "el hotel", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "hotel"},
    {"french": "l'auberge de jeunesse", "english": "youth hostel", "spanish": "el albergue juvenil", "gender": "f", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "albergue"},
    {"french": "le guide", "english": "guide", "spanish": "el guía", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "guía"},
    {"french": "l'excursion", "english": "excursion/trip", "spanish": "la excursión", "gender": "f", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "excursión"},
    {"french": "le souvenir", "english": "souvenir/memory", "spanish": "el recuerdo", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "souvenir"},
    {"french": "la carte", "english": "map", "spanish": "el mapa", "gender": "f", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "carta"},
    {"french": "le passeport", "english": "passport", "spanish": "el pasaporte", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "pasaporte"},
    {"french": "le visa", "english": "visa", "spanish": "la visa", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "visa"},
    {"french": "la douane", "english": "customs", "spanish": "la aduana", "gender": "f", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "aduana"},
    {"french": "le bagage", "english": "luggage", "spanish": "el equipaje", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "bagaje"},
    {"french": "la valise", "english": "suitcase", "spanish": "la maleta", "gender": "f", "part_of_speech": "noun", "category": "travel", "is_cognate": False},
    {"french": "l'itinéraire", "english": "itinerary", "spanish": "el itinerario", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "itinerario"},
    {"french": "le décalage horaire", "english": "jet lag", "spanish": "el jet lag", "gender": "m", "part_of_speech": "noun", "category": "travel", "is_cognate": False},
    {"french": "la croisière", "english": "cruise", "spanish": "el crucero", "gender": "f", "part_of_speech": "noun", "category": "travel", "is_cognate": True, "cognate_spanish": "crucero"},
    {"french": "découvrir", "english": "to discover", "spanish": "descubrir", "gender": "-", "part_of_speech": "verb", "category": "travel", "is_cognate": True, "cognate_spanish": "descubrir"},

    # Social Issues (15 items)
    {"french": "la société", "english": "society", "spanish": "la sociedad", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "sociedad"},
    {"french": "l'inégalité", "english": "inequality", "spanish": "la desigualdad", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "desigualdad"},
    {"french": "la pauvreté", "english": "poverty", "spanish": "la pobreza", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": False},
    {"french": "le sans-abri", "english": "homeless person", "spanish": "el sin hogar", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": False},
    {"french": "la discrimination", "english": "discrimination", "spanish": "la discriminación", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "discriminación"},
    {"french": "l'intégration", "english": "integration", "spanish": "la integración", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "integración"},
    {"french": "l'immigration", "english": "immigration", "spanish": "la inmigración", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "inmigración"},
    {"french": "le bénévolat", "english": "volunteering", "spanish": "el voluntariado", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "voluntariado"},
    {"french": "l'association", "english": "association/organization", "spanish": "la asociación", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "asociación"},
    {"french": "la solidarité", "english": "solidarity", "spanish": "la solidaridad", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "solidaridad"},
    {"french": "le droit", "english": "right", "spanish": "el derecho", "gender": "m", "part_of_speech": "noun", "category": "social", "is_cognate": False},
    {"french": "la manifestation", "english": "demonstration/protest", "spanish": "la manifestación", "gender": "f", "part_of_speech": "noun", "category": "social", "is_cognate": True, "cognate_spanish": "manifestación"},
    {"french": "revendiquer", "english": "to demand/claim", "spanish": "reivindicar", "gender": "-", "part_of_speech": "verb", "category": "social", "is_cognate": True, "cognate_spanish": "reivindicar"},
    {"french": "soutenir", "english": "to support", "spanish": "apoyar", "gender": "-", "part_of_speech": "verb", "category": "social", "is_cognate": False},
    {"french": "lutter", "english": "to fight/struggle", "spanish": "luchar", "gender": "-", "part_of_speech": "verb", "category": "social", "is_cognate": True, "cognate_spanish": "luchar"},
]
