"""
Colloquial French Vocabulary - "Street French"
Informal expressions, slang, and spoken French not typically taught in textbooks.
Essential for understanding real-world French conversations.

Organized by CEFR level from basic informal expressions to advanced slang.
"""

# ============ A1 LEVEL - Basic Informal Expressions ============
COLLOQUIAL_A1 = [
    {
        "french": "ouais",
        "english": "yeah (informal yes)",
        "spanish": "sí (informal)",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "wɛ",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Very common informal 'yes'. Used constantly in casual speech instead of 'oui'.",
        "example_french": "Tu viens ? — Ouais, j'arrive !",
        "example_english": "Are you coming? — Yeah, I'm coming!",
        "example_spanish": "¿Vienes? — ¡Sí, ya voy!"
    },
    {
        "french": "ben",
        "english": "well / uh (filler word)",
        "spanish": "pues / bueno",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "bɛ̃",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Short for 'bien'. Used as a filler word like 'well' or 'uh' in English.",
        "example_french": "Ben, je sais pas...",
        "example_english": "Well, I don't know...",
        "example_spanish": "Pues, no sé..."
    },
    {
        "french": "bof",
        "english": "meh / so-so / not really",
        "spanish": "bah / más o menos",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "bɔf",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Expresses indifference or lack of enthusiasm. Very French!",
        "example_french": "C'était bien ? — Bof, pas terrible.",
        "example_english": "Was it good? — Meh, not great.",
        "example_spanish": "¿Estuvo bien? — Bah, no mucho."
    },
    {
        "french": "coucou",
        "english": "hey / hi there (cute greeting)",
        "spanish": "¡hola! (cariñoso)",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "ku.ku",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Friendly, informal greeting. Often used with friends and family.",
        "example_french": "Coucou ! Ça va ?",
        "example_english": "Hey there! How are you?",
        "example_spanish": "¡Hola! ¿Qué tal?"
    },
    {
        "french": "bisou",
        "english": "kiss (informal)",
        "spanish": "besito",
        "gender": "masculine",
        "part_of_speech": "noun",
        "phonetic": "bi.zu",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Informal word for kiss. 'Bisous' (plural) is used to sign off messages.",
        "example_french": "Gros bisous !",
        "example_english": "Big kisses!",
        "example_spanish": "¡Muchos besitos!"
    },
    {
        "french": "sympa",
        "english": "nice / cool (person or thing)",
        "spanish": "simpático / genial",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "sɛ̃.pa",
        "category": "colloquial",
        "is_cognate": True,
        "cognate_spanish": "simpático",
        "cognate_note": "Short for 'sympathique', cognate with Spanish 'simpático'",
        "notes": "Shortened from 'sympathique'. Used for people and things.",
        "example_french": "Il est super sympa !",
        "example_english": "He's really nice!",
        "example_spanish": "¡Es muy simpático!"
    },
    {
        "french": "super",
        "english": "great / really (intensifier)",
        "spanish": "súper",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "sy.pɛʁ",
        "category": "colloquial",
        "is_cognate": True,
        "cognate_spanish": "súper",
        "notes": "Used as an intensifier: 'super bon', 'super bien', 'super cool'.",
        "example_french": "C'est super bon !",
        "example_english": "It's really good!",
        "example_spanish": "¡Está súper bueno!"
    },
    {
        "french": "t'inquiète",
        "english": "don't worry (about it)",
        "spanish": "no te preocupes",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "tɛ̃.kjɛt",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Short for 'ne t'inquiète pas'. Very common reassurance phrase.",
        "example_french": "T'inquiète, je m'en occupe !",
        "example_english": "Don't worry, I'll take care of it!",
        "example_spanish": "No te preocupes, yo me encargo."
    },
]

# ============ A2 LEVEL - Common Informal Expressions ============
COLLOQUIAL_A2 = [
    {
        "french": "bosser",
        "english": "to work (slang)",
        "spanish": "currar / trabajar",
        "gender": "-",
        "part_of_speech": "verb",
        "phonetic": "bɔ.se",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Informal for 'travailler'. Very commonly used.",
        "example_french": "Je dois bosser ce weekend.",
        "example_english": "I have to work this weekend.",
        "example_spanish": "Tengo que currar este fin de semana."
    },
    {
        "french": "bouffer",
        "english": "to eat / to scarf down",
        "spanish": "zampar / comer",
        "gender": "-",
        "part_of_speech": "verb",
        "phonetic": "bu.fe",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Slang for 'manger'. Implies eating a lot or quickly.",
        "example_french": "On va bouffer quelque chose ?",
        "example_english": "Shall we grab something to eat?",
        "example_spanish": "¿Vamos a comer algo?"
    },
    {
        "french": "la bouffe",
        "english": "food / grub",
        "spanish": "la comida / la manduca",
        "gender": "feminine",
        "part_of_speech": "noun",
        "phonetic": "buf",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Slang for food. From 'bouffer'.",
        "example_french": "La bouffe était délicieuse !",
        "example_english": "The food was delicious!",
        "example_spanish": "¡La comida estaba deliciosa!"
    },
    {
        "french": "un truc",
        "english": "a thing / stuff",
        "spanish": "una cosa / un rollo",
        "gender": "masculine",
        "part_of_speech": "noun",
        "phonetic": "tʁyk",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Generic word for 'thing'. Extremely common in spoken French.",
        "example_french": "C'est quoi ce truc ?",
        "example_english": "What's this thing?",
        "example_spanish": "¿Qué es esta cosa?"
    },
    {
        "french": "un mec",
        "english": "a guy / a dude",
        "spanish": "un tío / un tipo",
        "gender": "masculine",
        "part_of_speech": "noun",
        "phonetic": "mɛk",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Informal word for man/guy. Also means 'boyfriend' in context.",
        "example_french": "C'est qui ce mec ?",
        "example_english": "Who's that guy?",
        "example_spanish": "¿Quién es ese tío?"
    },
    {
        "french": "une meuf",
        "english": "a girl / a woman (slang)",
        "spanish": "una tía / una chica",
        "gender": "feminine",
        "part_of_speech": "noun",
        "phonetic": "mœf",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Verlan (reversed slang) for 'femme'. Common youth slang.",
        "example_french": "Sa meuf est super sympa.",
        "example_english": "His girlfriend is really nice.",
        "example_spanish": "Su novia es muy simpática."
    },
    {
        "french": "kiffer",
        "english": "to love / to really like",
        "spanish": "flipar / molar",
        "gender": "-",
        "part_of_speech": "verb",
        "phonetic": "ki.fe",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Youth slang meaning to really enjoy something. From Arabic 'kif'.",
        "example_french": "Je kiffe cette chanson !",
        "example_english": "I love this song!",
        "example_spanish": "¡Me flipa esta canción!"
    },
    {
        "french": "nickel",
        "english": "perfect / spotless",
        "spanish": "perfecto / impecable",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ni.kɛl",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Means 'perfect' or 'spotless'. From the shiny metal.",
        "example_french": "C'est nickel ! Merci !",
        "example_english": "That's perfect! Thanks!",
        "example_spanish": "¡Perfecto! ¡Gracias!"
    },
    {
        "french": "grave",
        "english": "really / seriously / totally",
        "spanish": "totalmente / en serio",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "gʁav",
        "category": "colloquial",
        "is_cognate": True,
        "cognate_spanish": "grave",
        "cognate_note": "Used differently - as intensifier in French slang",
        "notes": "Used as an intensifier in slang. 'Grave bien' = really good.",
        "example_french": "C'était grave bien !",
        "example_english": "It was really good!",
        "example_spanish": "¡Estuvo genial!"
    },
    {
        "french": "je m'en fiche",
        "english": "I don't care",
        "spanish": "me da igual",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ʒə mɑ̃ fiʃ",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Polite way to say 'I don't care'. More vulgar: 'je m'en fous'.",
        "example_french": "Ce qu'il pense ? Je m'en fiche !",
        "example_english": "What he thinks? I don't care!",
        "example_spanish": "¿Lo que piensa él? ¡Me da igual!"
    },
]

# ============ B1 LEVEL - Everyday Informal Language ============
COLLOQUIAL_B1 = [
    {
        "french": "j'en ai marre",
        "english": "I'm fed up / I've had enough",
        "spanish": "estoy harto",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ʒɑ̃ ne maʁ",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Very common expression of frustration.",
        "example_french": "J'en ai marre de ce boulot !",
        "example_english": "I'm fed up with this job!",
        "example_spanish": "¡Estoy harto de este trabajo!"
    },
    {
        "french": "le boulot",
        "english": "work / job (informal)",
        "spanish": "el curro / el trabajo",
        "gender": "masculine",
        "part_of_speech": "noun",
        "phonetic": "bu.lo",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Very common slang for 'travail'.",
        "example_french": "Je vais au boulot.",
        "example_english": "I'm going to work.",
        "example_spanish": "Voy al trabajo."
    },
    {
        "french": "se planter",
        "english": "to mess up / to fail",
        "spanish": "cagarla / meter la pata",
        "gender": "-",
        "part_of_speech": "verb",
        "phonetic": "sə plɑ̃.te",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To fail or make a mistake. Also 'se planter en voiture' = to crash.",
        "example_french": "Je me suis planté à l'examen.",
        "example_english": "I failed the exam.",
        "example_spanish": "La cagué en el examen."
    },
    {
        "french": "la galère",
        "english": "hassle / nightmare / struggle",
        "spanish": "el rollo / la movida",
        "gender": "feminine",
        "part_of_speech": "noun",
        "phonetic": "ga.lɛʁ",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Describes a difficult situation. 'C'est la galère' = what a hassle.",
        "example_french": "Trouver un appartement à Paris, c'est la galère !",
        "example_english": "Finding an apartment in Paris is such a hassle!",
        "example_spanish": "¡Encontrar piso en París es un rollo!"
    },
    {
        "french": "se faire chier",
        "english": "to be bored / to have a terrible time",
        "spanish": "aburrirse / pasarlo mal",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sə fɛʁ ʃje",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Vulgar but very common. Means being very bored.",
        "example_french": "Je me fais chier ici.",
        "example_english": "I'm so bored here.",
        "example_spanish": "Me aburro aquí."
    },
    {
        "french": "n'importe quoi",
        "english": "whatever / nonsense / anything",
        "spanish": "cualquier cosa / tonterías",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "nɛ̃.pɔʁt kwa",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Can mean 'anything' or as exclamation 'that's ridiculous!'",
        "example_french": "Tu racontes n'importe quoi !",
        "example_english": "You're talking nonsense!",
        "example_spanish": "¡Estás diciendo tonterías!"
    },
    {
        "french": "être à la bourre",
        "english": "to be running late",
        "spanish": "ir con retraso",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ɛtʁ a la buʁ",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Very common expression. 'Je suis à la bourre!'",
        "example_french": "Dépêche-toi, on est à la bourre !",
        "example_english": "Hurry up, we're running late!",
        "example_spanish": "¡Date prisa, vamos con retraso!"
    },
    {
        "french": "ça craint",
        "english": "that sucks / that's lame",
        "spanish": "eso apesta / es una mierda",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sa kʁɛ̃",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Express that something is bad or worrying.",
        "example_french": "Il pleut encore ? Ça craint !",
        "example_english": "It's raining again? That sucks!",
        "example_spanish": "¿Llueve otra vez? ¡Qué rollo!"
    },
    {
        "french": "péter un câble",
        "english": "to lose it / to snap / to freak out",
        "spanish": "perder los papeles / volverse loco",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "pe.te œ̃ kabl",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To suddenly lose one's temper or go crazy.",
        "example_french": "Mon père va péter un câble !",
        "example_english": "My dad is going to lose it!",
        "example_spanish": "¡Mi padre va a volverse loco!"
    },
    {
        "french": "un pote",
        "english": "a buddy / a pal",
        "spanish": "un colega / un amigo",
        "gender": "masculine",
        "part_of_speech": "noun",
        "phonetic": "pɔt",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Informal for friend. Very common.",
        "example_french": "Je sors avec mes potes.",
        "example_english": "I'm going out with my buddies.",
        "example_spanish": "Salgo con mis colegas."
    },
]

# ============ B2 LEVEL - Advanced Informal Language ============
COLLOQUIAL_B2 = [
    {
        "french": "se la péter",
        "english": "to show off / to be full of oneself",
        "spanish": "darse aires / creérselo",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sə la pe.te",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To act arrogantly or show off.",
        "example_french": "Il se la pète depuis sa promotion.",
        "example_english": "He's been showing off since his promotion.",
        "example_spanish": "Se lo cree desde su ascenso."
    },
    {
        "french": "être dans la merde",
        "english": "to be in deep trouble",
        "spanish": "estar en la mierda / estar jodido",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ɛtʁ dɑ̃ la mɛʁd",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Vulgar but extremely common. Being in serious trouble.",
        "example_french": "Si je rate cet exam, je suis dans la merde.",
        "example_english": "If I fail this exam, I'm in deep trouble.",
        "example_spanish": "Si suspendo este examen, estoy jodido."
    },
    {
        "french": "avoir le cafard",
        "english": "to feel down / to be depressed",
        "spanish": "estar depre / tener morriña",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "a.vwaʁ lə ka.faʁ",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "'Cafard' literally means cockroach. Expresses feeling blue.",
        "example_french": "J'ai le cafard aujourd'hui.",
        "example_english": "I'm feeling down today.",
        "example_spanish": "Hoy estoy depre."
    },
    {
        "french": "se casser",
        "english": "to leave / to get out of here",
        "spanish": "pirarse / largarse",
        "gender": "-",
        "part_of_speech": "verb",
        "phonetic": "sə ka.se",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Informal way to say 'to leave'. 'Je me casse!' = I'm out of here!",
        "example_french": "Allez, je me casse !",
        "example_english": "Alright, I'm out of here!",
        "example_spanish": "¡Venga, me piro!"
    },
    {
        "french": "bourré(e)",
        "english": "drunk / wasted",
        "spanish": "borracho / pedo",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "bu.ʁe",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Very common slang for being drunk.",
        "example_french": "Il était complètement bourré hier soir.",
        "example_english": "He was completely wasted last night.",
        "example_spanish": "Estaba totalmente borracho anoche."
    },
    {
        "french": "se prendre la tête",
        "english": "to overthink / to get stressed out",
        "spanish": "comerse el coco / rayarse",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sə pʁɑ̃dʁ la tɛt",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To stress out or overthink. Also 'se prendre la tête avec quelqu'un' = to argue.",
        "example_french": "Arrête de te prendre la tête !",
        "example_english": "Stop overthinking it!",
        "example_spanish": "¡Deja de comerte el coco!"
    },
    {
        "french": "une arnaque",
        "english": "a scam / a rip-off",
        "spanish": "un timo / una estafa",
        "gender": "feminine",
        "part_of_speech": "noun",
        "phonetic": "aʁ.nak",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "A scam or rip-off. 'C'est une arnaque!' = What a rip-off!",
        "example_french": "Ce restaurant, c'est une arnaque totale !",
        "example_english": "This restaurant is a total rip-off!",
        "example_spanish": "¡Este restaurante es un timo total!"
    },
    {
        "french": "un(e) con(ne)",
        "english": "an idiot / a jerk (vulgar)",
        "spanish": "un/una imbécil / gilipollas",
        "gender": "-",
        "part_of_speech": "noun",
        "phonetic": "kɔ̃ / kɔn",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Vulgar but extremely common insult. Handle with care!",
        "example_french": "Quel con ce type !",
        "example_english": "What an idiot that guy is!",
        "example_spanish": "¡Qué imbécil ese tío!"
    },
    {
        "french": "draguer",
        "english": "to hit on / to flirt with",
        "spanish": "ligar / tirar los tejos",
        "gender": "-",
        "part_of_speech": "verb",
        "phonetic": "dʁa.ge",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To flirt with someone, try to pick them up.",
        "example_french": "Il essaie de la draguer.",
        "example_english": "He's trying to hit on her.",
        "example_spanish": "Está intentando ligar con ella."
    },
    {
        "french": "être au courant",
        "english": "to be in the know / to be aware",
        "spanish": "estar al tanto / enterarse",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ɛtʁ o ku.ʁɑ̃",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To be aware of something. 'Tu es au courant?' = Did you hear?",
        "example_french": "Tu es au courant pour Marc et Julie ?",
        "example_english": "Did you hear about Marc and Julie?",
        "example_spanish": "¿Te has enterado de lo de Marc y Julie?"
    },
]

# ============ C1 LEVEL - Sophisticated Informal Language ============
COLLOQUIAL_C1 = [
    {
        "french": "ça me saoule",
        "english": "it's getting on my nerves / it's annoying me",
        "spanish": "me raya / me agobia",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sa mə sul",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "From 'saouler' (to get drunk). Means something is annoying you greatly.",
        "example_french": "Ce bruit me saoule !",
        "example_english": "This noise is driving me crazy!",
        "example_spanish": "¡Este ruido me raya!"
    },
    {
        "french": "c'est du n'importe quoi",
        "english": "this is ridiculous / this makes no sense",
        "spanish": "esto no tiene sentido / es absurdo",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sɛ dy nɛ̃.pɔʁt kwa",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Expresses that something is completely absurd or unacceptable.",
        "example_french": "Cette nouvelle loi, c'est du n'importe quoi !",
        "example_english": "This new law is ridiculous!",
        "example_spanish": "¡Esta nueva ley es absurda!"
    },
    {
        "french": "être en décalage",
        "english": "to be out of sync / out of touch",
        "spanish": "estar desfasado / desconectado",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ɛtʁ ɑ̃ de.ka.laʒ",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To feel disconnected from a situation or group.",
        "example_french": "Je me sens en décalage avec ma génération.",
        "example_english": "I feel out of touch with my generation.",
        "example_spanish": "Me siento desfasado con mi generación."
    },
    {
        "french": "se faire arnaquer",
        "english": "to get ripped off / scammed",
        "spanish": "que te timen / te estafen",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sə fɛʁ aʁ.na.ke",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To be swindled or cheated.",
        "example_french": "Je me suis fait arnaquer par ce vendeur.",
        "example_english": "I got ripped off by that seller.",
        "example_spanish": "Me timó ese vendedor."
    },
    {
        "french": "avoir la flemme",
        "english": "to feel lazy / can't be bothered",
        "spanish": "tener pereza / no tener ganas",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "a.vwaʁ la flɛm",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Very common. To not feel like doing something.",
        "example_french": "J'ai la flemme de sortir ce soir.",
        "example_english": "I can't be bothered to go out tonight.",
        "example_spanish": "No tengo ganas de salir esta noche."
    },
    {
        "french": "foutre le bordel",
        "english": "to cause chaos / to mess things up",
        "spanish": "liar parda / montar un follón",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "futʁ lə bɔʁ.dɛl",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Vulgar. To create disorder or chaos.",
        "example_french": "Il a foutu le bordel dans le bureau.",
        "example_english": "He caused chaos in the office.",
        "example_spanish": "Lió parda en la oficina."
    },
    {
        "french": "c'est prise de tête",
        "english": "it's a headache / it's complicated",
        "spanish": "es un dolor de cabeza / es complicado",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sɛ pʁiz də tɛt",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Describes something mentally exhausting or complicated.",
        "example_french": "Les impôts, c'est trop prise de tête !",
        "example_english": "Taxes are such a headache!",
        "example_spanish": "¡Los impuestos son un dolor de cabeza!"
    },
    {
        "french": "laisser tomber",
        "english": "to drop it / to give up on",
        "spanish": "dejarlo / pasar de algo",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "le.se tɔ̃.be",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To abandon or stop trying. 'Laisse tomber!' = Forget about it!",
        "example_french": "Laisse tomber, ça ne vaut pas la peine.",
        "example_english": "Drop it, it's not worth it.",
        "example_spanish": "Déjalo, no vale la pena."
    },
    {
        "french": "être au taquet",
        "english": "to be pumped / to be at maximum",
        "spanish": "estar a tope / estar motivado",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ɛtʁ o ta.kɛ",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To be at full capacity or very motivated.",
        "example_french": "Je suis au taquet pour ce projet !",
        "example_english": "I'm pumped for this project!",
        "example_spanish": "¡Estoy a tope con este proyecto!"
    },
    {
        "french": "se faire des films",
        "english": "to imagine things / to overthink",
        "spanish": "imaginarse cosas / montarse películas",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sə fɛʁ de film",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To imagine scenarios that aren't real.",
        "example_french": "Arrête de te faire des films, il ne t'a pas oublié.",
        "example_english": "Stop imagining things, he hasn't forgotten you.",
        "example_spanish": "Deja de montarte películas, no te ha olvidado."
    },
]

# ============ C2 LEVEL - Native-Level Informal Language ============
COLLOQUIAL_C2 = [
    {
        "french": "c'est du flan",
        "english": "it's all talk / it's BS",
        "spanish": "es puro cuento / es paja",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sɛ dy flɑ̃",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Something that's not serious or is made up.",
        "example_french": "Ses promesses, c'est du flan !",
        "example_english": "His promises are all talk!",
        "example_spanish": "¡Sus promesas son puro cuento!"
    },
    {
        "french": "ne pas y aller par quatre chemins",
        "english": "to not beat around the bush",
        "spanish": "no andarse con rodeos",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "nə pa i a.le paʁ katʁ ʃə.mɛ̃",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To be direct and straightforward.",
        "example_french": "Je n'y vais pas par quatre chemins : tu as tort.",
        "example_english": "I won't beat around the bush: you're wrong.",
        "example_spanish": "No me ando con rodeos: estás equivocado."
    },
    {
        "french": "rouler quelqu'un dans la farine",
        "english": "to take someone for a ride / to swindle",
        "spanish": "tomar el pelo / engañar",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ʁu.le kɛl.kœ̃ dɑ̃ la fa.ʁin",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Literally 'to roll someone in flour'. To deceive cleverly.",
        "example_french": "Le vendeur nous a roulés dans la farine.",
        "example_english": "The salesman took us for a ride.",
        "example_spanish": "El vendedor nos tomó el pelo."
    },
    {
        "french": "mettre les pieds dans le plat",
        "english": "to put one's foot in it / to be tactless",
        "spanish": "meter la pata / ser inoportuno",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "mɛtʁ le pje dɑ̃ lə pla",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To say something inappropriate or tactless.",
        "example_french": "Comme d'habitude, il a mis les pieds dans le plat.",
        "example_english": "As usual, he put his foot in it.",
        "example_spanish": "Como siempre, metió la pata."
    },
    {
        "french": "être à côté de la plaque",
        "english": "to be off the mark / clueless",
        "spanish": "estar en la inopia / no enterarse",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ɛtʁ a ko.te də la plak",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To completely miss the point or be out of touch.",
        "example_french": "Sa réponse était complètement à côté de la plaque.",
        "example_english": "His answer was completely off the mark.",
        "example_spanish": "Su respuesta estaba totalmente fuera de lugar."
    },
    {
        "french": "c'est kif-kif",
        "english": "it's all the same / six of one, half a dozen of the other",
        "spanish": "es lo mismo / da igual",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sɛ kif kif",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "From Arabic. Means two things are the same.",
        "example_french": "Prendre le bus ou le métro, c'est kif-kif.",
        "example_english": "Taking the bus or the metro is all the same.",
        "example_spanish": "Coger el bus o el metro es lo mismo."
    },
    {
        "french": "péter plus haut que son cul",
        "english": "to be too big for one's boots / to be pretentious",
        "spanish": "creerse mejor de lo que es / darse aires",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "pe.te ply o kə sɔ̃ kyl",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Vulgar. To act above one's station.",
        "example_french": "Depuis sa promotion, il pète plus haut que son cul.",
        "example_english": "Since his promotion, he's gotten too big for his boots.",
        "example_spanish": "Desde su ascenso, se cree mejor de lo que es."
    },
    {
        "french": "retourner sa veste",
        "english": "to do a U-turn / to change sides",
        "spanish": "cambiar de chaqueta / volverse atrás",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ʁə.tuʁ.ne sa vɛst",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To change one's position or allegiance opportunistically.",
        "example_french": "Ce politicien a encore retourné sa veste.",
        "example_english": "That politician has done another U-turn.",
        "example_spanish": "Ese político ha cambiado de chaqueta otra vez."
    },
    {
        "french": "couper les cheveux en quatre",
        "english": "to split hairs / to be overly precise",
        "spanish": "hilar muy fino / buscar tres pies al gato",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ku.pe le ʃə.vø ɑ̃ katʁ",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "To be excessively detailed or nitpicky.",
        "example_french": "Arrête de couper les cheveux en quatre !",
        "example_english": "Stop splitting hairs!",
        "example_spanish": "¡Deja de buscar tres pies al gato!"
    },
    {
        "french": "prendre quelqu'un pour un jambon",
        "english": "to take someone for a fool",
        "spanish": "tomar a alguien por tonto",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "pʁɑ̃dʁ kɛl.kœ̃ puʁ œ̃ ʒɑ̃.bɔ̃",
        "category": "colloquial",
        "is_cognate": False,
        "notes": "Literally 'to take someone for a ham'. To think someone is stupid.",
        "example_french": "Tu me prends pour un jambon ou quoi ?",
        "example_english": "Do you take me for a fool or what?",
        "example_spanish": "¿Me tomas por tonto o qué?"
    },
]

# Combined dictionary for easy access
COLLOQUIAL_BY_LEVEL = {
    "A1": COLLOQUIAL_A1,
    "A2": COLLOQUIAL_A2,
    "B1": COLLOQUIAL_B1,
    "B2": COLLOQUIAL_B2,
    "C1": COLLOQUIAL_C1,
    "C2": COLLOQUIAL_C2,
}
