"""
A2 Level Vocabulary - Elementary
Alliance Française A200-A205 equivalent
Expanded content for sustained practice sessions
"""

VOCABULARY_A2 = [
    # Daily Routines & Activities (20 items)
    {"french": "se réveiller", "english": "to wake up", "spanish": "despertarse", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": False, "example_french": "Je me réveille à sept heures.", "example_english": "I wake up at seven o'clock."},
    {"french": "se coucher", "english": "to go to bed", "spanish": "acostarse", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": False, "example_french": "Elle se couche tard.", "example_english": "She goes to bed late."},
    {"french": "se doucher", "english": "to shower", "spanish": "ducharse", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": False},
    {"french": "se brosser les dents", "english": "to brush one's teeth", "spanish": "cepillarse los dientes", "gender": "-", "part_of_speech": "phrase", "category": "daily_routines", "is_cognate": False},
    {"french": "s'habiller", "english": "to get dressed", "spanish": "vestirse", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": False},
    {"french": "se préparer", "english": "to get ready", "spanish": "prepararse", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": True, "cognate_spanish": "prepararse"},
    {"french": "se maquiller", "english": "to put on makeup", "spanish": "maquillarse", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": True, "cognate_spanish": "maquillarse"},
    {"french": "se raser", "english": "to shave", "spanish": "afeitarse", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": False},
    {"french": "se peigner", "english": "to comb one's hair", "spanish": "peinarse", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": True, "cognate_spanish": "peinarse"},
    {"french": "se lever", "english": "to get up", "spanish": "levantarse", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": False, "example_french": "Je me lève tôt.", "example_english": "I get up early."},
    {"french": "prendre le petit déjeuner", "english": "to have breakfast", "spanish": "desayunar", "gender": "-", "part_of_speech": "phrase", "category": "daily_routines", "is_cognate": False},
    {"french": "se dépêcher", "english": "to hurry", "spanish": "darse prisa", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": False},
    {"french": "se reposer", "english": "to rest", "spanish": "descansar", "gender": "-", "part_of_speech": "verb", "category": "daily_routines", "is_cognate": True, "cognate_spanish": "reposar"},
    {"french": "faire la sieste", "english": "to take a nap", "spanish": "echar la siesta", "gender": "-", "part_of_speech": "phrase", "category": "daily_routines", "is_cognate": True, "cognate_spanish": "siesta"},
    {"french": "le réveil", "english": "alarm clock", "spanish": "el despertador", "gender": "m", "part_of_speech": "noun", "category": "daily_routines", "is_cognate": False},
    {"french": "la routine", "english": "routine", "spanish": "la rutina", "gender": "f", "part_of_speech": "noun", "category": "daily_routines", "is_cognate": True, "cognate_spanish": "rutina"},
    {"french": "quotidien", "english": "daily", "spanish": "cotidiano", "gender": "m", "part_of_speech": "adjective", "category": "daily_routines", "is_cognate": True, "cognate_spanish": "cotidiano"},
    {"french": "tôt", "english": "early", "spanish": "temprano", "gender": "-", "part_of_speech": "adverb", "category": "daily_routines", "is_cognate": False},
    {"french": "tard", "english": "late", "spanish": "tarde", "gender": "-", "part_of_speech": "adverb", "category": "daily_routines", "is_cognate": True, "cognate_spanish": "tarde"},
    {"french": "d'habitude", "english": "usually", "spanish": "normalmente", "gender": "-", "part_of_speech": "adverb", "category": "daily_routines", "is_cognate": False},

    # Shopping & Commerce (25 items)
    {"french": "le magasin", "english": "store/shop", "spanish": "la tienda", "gender": "m", "part_of_speech": "noun", "category": "shopping", "is_cognate": False, "example_french": "Le magasin ouvre à neuf heures.", "example_english": "The store opens at nine o'clock."},
    {"french": "la boulangerie", "english": "bakery", "spanish": "la panadería", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": False},
    {"french": "la pharmacie", "english": "pharmacy", "spanish": "la farmacia", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "farmacia"},
    {"french": "le supermarché", "english": "supermarket", "spanish": "el supermercado", "gender": "m", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "supermercado"},
    {"french": "acheter", "english": "to buy", "spanish": "comprar", "gender": "-", "part_of_speech": "verb", "category": "shopping", "is_cognate": False},
    {"french": "vendre", "english": "to sell", "spanish": "vender", "gender": "-", "part_of_speech": "verb", "category": "shopping", "is_cognate": True, "cognate_spanish": "vender"},
    {"french": "le prix", "english": "price", "spanish": "el precio", "gender": "m", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "precio"},
    {"french": "cher", "english": "expensive", "spanish": "caro", "gender": "m", "part_of_speech": "adjective", "category": "shopping", "is_cognate": False},
    {"french": "bon marché", "english": "cheap/inexpensive", "spanish": "barato", "gender": "-", "part_of_speech": "adjective", "category": "shopping", "is_cognate": False},
    {"french": "la boucherie", "english": "butcher shop", "spanish": "la carnicería", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": False},
    {"french": "la pâtisserie", "english": "pastry shop", "spanish": "la pastelería", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "pastelería"},
    {"french": "la librairie", "english": "bookstore", "spanish": "la librería", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "librería"},
    {"french": "le marché", "english": "market", "spanish": "el mercado", "gender": "m", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "mercado"},
    {"french": "la caisse", "english": "cash register/checkout", "spanish": "la caja", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "caja"},
    {"french": "le vendeur", "english": "salesperson (m)", "spanish": "el vendedor", "gender": "m", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "vendedor"},
    {"french": "la vendeuse", "english": "salesperson (f)", "spanish": "la vendedora", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "vendedora"},
    {"french": "le client", "english": "customer", "spanish": "el cliente", "gender": "m", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "cliente"},
    {"french": "payer", "english": "to pay", "spanish": "pagar", "gender": "-", "part_of_speech": "verb", "category": "shopping", "is_cognate": True, "cognate_spanish": "pagar"},
    {"french": "la monnaie", "english": "change/currency", "spanish": "el cambio/la moneda", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "moneda"},
    {"french": "le reçu", "english": "receipt", "spanish": "el recibo", "gender": "m", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "recibo"},
    {"french": "la réduction", "english": "discount", "spanish": "el descuento", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "reducción"},
    {"french": "les soldes", "english": "sales", "spanish": "las rebajas", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": False},
    {"french": "gratuit", "english": "free (no cost)", "spanish": "gratis", "gender": "m", "part_of_speech": "adjective", "category": "shopping", "is_cognate": True, "cognate_spanish": "gratis"},
    {"french": "la taille", "english": "size", "spanish": "la talla", "gender": "f", "part_of_speech": "noun", "category": "shopping", "is_cognate": True, "cognate_spanish": "talla"},
    {"french": "essayer", "english": "to try on", "spanish": "probar", "gender": "-", "part_of_speech": "verb", "category": "shopping", "is_cognate": False},

    # Transportation (25 items)
    {"french": "le train", "english": "train", "spanish": "el tren", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "tren"},
    {"french": "le bus", "english": "bus", "spanish": "el autobús", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "bus"},
    {"french": "le métro", "english": "subway/metro", "spanish": "el metro", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "metro"},
    {"french": "l'avion", "english": "airplane", "spanish": "el avión", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "avión"},
    {"french": "le billet", "english": "ticket", "spanish": "el billete", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "billete"},
    {"french": "la gare", "english": "train station", "spanish": "la estación", "gender": "f", "part_of_speech": "noun", "category": "transportation", "is_cognate": False},
    {"french": "l'aéroport", "english": "airport", "spanish": "el aeropuerto", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "aeropuerto"},
    {"french": "partir", "english": "to leave/depart", "spanish": "partir", "gender": "-", "part_of_speech": "verb", "category": "transportation", "is_cognate": True, "cognate_spanish": "partir"},
    {"french": "arriver", "english": "to arrive", "spanish": "llegar", "gender": "-", "part_of_speech": "verb", "category": "transportation", "is_cognate": False},
    {"french": "le taxi", "english": "taxi", "spanish": "el taxi", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "taxi"},
    {"french": "le tramway", "english": "tram", "spanish": "el tranvía", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "tranvía"},
    {"french": "le vélo", "english": "bicycle", "spanish": "la bicicleta", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": False},
    {"french": "la moto", "english": "motorcycle", "spanish": "la moto", "gender": "f", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "moto"},
    {"french": "le bateau", "english": "boat", "spanish": "el barco", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": False},
    {"french": "l'arrêt de bus", "english": "bus stop", "spanish": "la parada de autobús", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": False},
    {"french": "la station de métro", "english": "metro station", "spanish": "la estación de metro", "gender": "f", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "estación"},
    {"french": "le quai", "english": "platform", "spanish": "el andén", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": False},
    {"french": "la correspondance", "english": "connection/transfer", "spanish": "el transbordo", "gender": "f", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "correspondencia"},
    {"french": "le retard", "english": "delay", "spanish": "el retraso", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "retraso"},
    {"french": "à l'heure", "english": "on time", "spanish": "a tiempo", "gender": "-", "part_of_speech": "phrase", "category": "transportation", "is_cognate": False},
    {"french": "en avance", "english": "early/ahead", "spanish": "temprano", "gender": "-", "part_of_speech": "phrase", "category": "transportation", "is_cognate": False},
    {"french": "en retard", "english": "late", "spanish": "tarde", "gender": "-", "part_of_speech": "phrase", "category": "transportation", "is_cognate": True, "cognate_spanish": "retardo"},
    {"french": "le conducteur", "english": "driver", "spanish": "el conductor", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "conductor"},
    {"french": "le passager", "english": "passenger", "spanish": "el pasajero", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "pasajero"},
    {"french": "le trajet", "english": "journey/trip", "spanish": "el trayecto", "gender": "m", "part_of_speech": "noun", "category": "transportation", "is_cognate": True, "cognate_spanish": "trayecto"},

    # Weather (20 items)
    {"french": "le temps", "english": "weather/time", "spanish": "el tiempo", "gender": "m", "part_of_speech": "noun", "category": "weather", "is_cognate": True, "cognate_spanish": "tiempo"},
    {"french": "il fait beau", "english": "it's nice weather", "spanish": "hace buen tiempo", "gender": "-", "part_of_speech": "phrase", "category": "weather", "is_cognate": False},
    {"french": "il fait chaud", "english": "it's hot", "spanish": "hace calor", "gender": "-", "part_of_speech": "phrase", "category": "weather", "is_cognate": False},
    {"french": "il fait froid", "english": "it's cold", "spanish": "hace frío", "gender": "-", "part_of_speech": "phrase", "category": "weather", "is_cognate": False},
    {"french": "il pleut", "english": "it's raining", "spanish": "llueve", "gender": "-", "part_of_speech": "phrase", "category": "weather", "is_cognate": False},
    {"french": "il neige", "english": "it's snowing", "spanish": "nieva", "gender": "-", "part_of_speech": "phrase", "category": "weather", "is_cognate": False},
    {"french": "le soleil", "english": "sun", "spanish": "el sol", "gender": "m", "part_of_speech": "noun", "category": "weather", "is_cognate": True, "cognate_spanish": "sol"},
    {"french": "la pluie", "english": "rain", "spanish": "la lluvia", "gender": "f", "part_of_speech": "noun", "category": "weather", "is_cognate": False},
    {"french": "le nuage", "english": "cloud", "spanish": "la nube", "gender": "m", "part_of_speech": "noun", "category": "weather", "is_cognate": False},
    {"french": "la neige", "english": "snow", "spanish": "la nieve", "gender": "f", "part_of_speech": "noun", "category": "weather", "is_cognate": False},
    {"french": "le vent", "english": "wind", "spanish": "el viento", "gender": "m", "part_of_speech": "noun", "category": "weather", "is_cognate": True, "cognate_spanish": "viento"},
    {"french": "il y a du vent", "english": "it's windy", "spanish": "hace viento", "gender": "-", "part_of_speech": "phrase", "category": "weather", "is_cognate": False},
    {"french": "l'orage", "english": "storm", "spanish": "la tormenta", "gender": "m", "part_of_speech": "noun", "category": "weather", "is_cognate": False},
    {"french": "le brouillard", "english": "fog", "spanish": "la niebla", "gender": "m", "part_of_speech": "noun", "category": "weather", "is_cognate": False},
    {"french": "ensoleillé", "english": "sunny", "spanish": "soleado", "gender": "m", "part_of_speech": "adjective", "category": "weather", "is_cognate": True, "cognate_spanish": "soleado"},
    {"french": "nuageux", "english": "cloudy", "spanish": "nublado", "gender": "m", "part_of_speech": "adjective", "category": "weather", "is_cognate": False},
    {"french": "pluvieux", "english": "rainy", "spanish": "lluvioso", "gender": "m", "part_of_speech": "adjective", "category": "weather", "is_cognate": False},
    {"french": "la température", "english": "temperature", "spanish": "la temperatura", "gender": "f", "part_of_speech": "noun", "category": "weather", "is_cognate": True, "cognate_spanish": "temperatura"},
    {"french": "le degré", "english": "degree", "spanish": "el grado", "gender": "m", "part_of_speech": "noun", "category": "weather", "is_cognate": True, "cognate_spanish": "grado"},
    {"french": "la météo", "english": "weather forecast", "spanish": "el pronóstico", "gender": "f", "part_of_speech": "noun", "category": "weather", "is_cognate": False},

    # Health & Body (25 items)
    {"french": "la tête", "english": "head", "spanish": "la cabeza", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "le bras", "english": "arm", "spanish": "el brazo", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "brazo"},
    {"french": "la jambe", "english": "leg", "spanish": "la pierna", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "le dos", "english": "back", "spanish": "la espalda", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "avoir mal", "english": "to hurt/have pain", "spanish": "tener dolor", "gender": "-", "part_of_speech": "phrase", "category": "health", "is_cognate": False, "example_french": "J'ai mal à la tête.", "example_english": "I have a headache."},
    {"french": "le médecin", "english": "doctor", "spanish": "el médico", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "médico"},
    {"french": "malade", "english": "sick/ill", "spanish": "enfermo", "gender": "-", "part_of_speech": "adjective", "category": "health", "is_cognate": False},
    {"french": "la santé", "english": "health", "spanish": "la salud", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "le ventre", "english": "stomach/belly", "spanish": "el vientre", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "vientre"},
    {"french": "la gorge", "english": "throat", "spanish": "la garganta", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "l'oreille", "english": "ear", "spanish": "la oreja", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "oreja"},
    {"french": "l'œil", "english": "eye", "spanish": "el ojo", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "les yeux", "english": "eyes", "spanish": "los ojos", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "le nez", "english": "nose", "spanish": "la nariz", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "la bouche", "english": "mouth", "spanish": "la boca", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "boca"},
    {"french": "le pied", "english": "foot", "spanish": "el pie", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "pie"},
    {"french": "la main", "english": "hand", "spanish": "la mano", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "mano"},
    {"french": "le doigt", "english": "finger", "spanish": "el dedo", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "le cœur", "english": "heart", "spanish": "el corazón", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "le rhume", "english": "cold (illness)", "spanish": "el resfriado", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "la fièvre", "english": "fever", "spanish": "la fiebre", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "fiebre"},
    {"french": "le médicament", "english": "medicine/medication", "spanish": "el medicamento", "gender": "m", "part_of_speech": "noun", "category": "health", "is_cognate": True, "cognate_spanish": "medicamento"},
    {"french": "l'ordonnance", "english": "prescription", "spanish": "la receta", "gender": "f", "part_of_speech": "noun", "category": "health", "is_cognate": False},
    {"french": "guérir", "english": "to heal/recover", "spanish": "curar", "gender": "-", "part_of_speech": "verb", "category": "health", "is_cognate": False},
    {"french": "se sentir", "english": "to feel", "spanish": "sentirse", "gender": "-", "part_of_speech": "verb", "category": "health", "is_cognate": True, "cognate_spanish": "sentirse"},

    # Describing People & Things (25 items)
    {"french": "grand", "english": "tall/big", "spanish": "grande", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "grande"},
    {"french": "petit", "english": "small/short", "spanish": "pequeño", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": False},
    {"french": "jeune", "english": "young", "spanish": "joven", "gender": "-", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "joven"},
    {"french": "vieux", "english": "old", "spanish": "viejo", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "viejo"},
    {"french": "beau", "english": "beautiful/handsome", "spanish": "bello", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "bello"},
    {"french": "nouveau", "english": "new", "spanish": "nuevo", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "nuevo"},
    {"french": "facile", "english": "easy", "spanish": "fácil", "gender": "-", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "fácil"},
    {"french": "difficile", "english": "difficult", "spanish": "difícil", "gender": "-", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "difícil"},
    {"french": "gros", "english": "fat/big", "spanish": "gordo", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": False},
    {"french": "mince", "english": "thin/slim", "spanish": "delgado", "gender": "-", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": False},
    {"french": "fort", "english": "strong", "spanish": "fuerte", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "fuerte"},
    {"french": "faible", "english": "weak", "spanish": "débil", "gender": "-", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": False},
    {"french": "long", "english": "long", "spanish": "largo", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": False},
    {"french": "court", "english": "short", "spanish": "corto", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "corto"},
    {"french": "lourd", "english": "heavy", "spanish": "pesado", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": False},
    {"french": "léger", "english": "light (weight)", "spanish": "ligero", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "ligero"},
    {"french": "rapide", "english": "fast", "spanish": "rápido", "gender": "-", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "rápido"},
    {"french": "lent", "english": "slow", "spanish": "lento", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "lento"},
    {"french": "propre", "english": "clean/own", "spanish": "limpio/propio", "gender": "-", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "propio"},
    {"french": "sale", "english": "dirty", "spanish": "sucio", "gender": "-", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": False},
    {"french": "chaud", "english": "hot/warm", "spanish": "caliente", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": False},
    {"french": "froid", "english": "cold", "spanish": "frío", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "frío"},
    {"french": "doux", "english": "soft/sweet", "spanish": "suave/dulce", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": False},
    {"french": "dur", "english": "hard", "spanish": "duro", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "duro"},
    {"french": "mouillé", "english": "wet", "spanish": "mojado", "gender": "m", "part_of_speech": "adjective", "category": "descriptions", "is_cognate": True, "cognate_spanish": "mojado"},

    # House & Home (25 items)
    {"french": "la maison", "english": "house", "spanish": "la casa", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "l'appartement", "english": "apartment", "spanish": "el apartamento", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "apartamento"},
    {"french": "la chambre", "english": "bedroom", "spanish": "la habitación", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "la cuisine", "english": "kitchen", "spanish": "la cocina", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "cocina"},
    {"french": "la salle de bain", "english": "bathroom", "spanish": "el baño", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "le salon", "english": "living room", "spanish": "el salón", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "salón"},
    {"french": "la salle à manger", "english": "dining room", "spanish": "el comedor", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "le jardin", "english": "garden", "spanish": "el jardín", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "jardín"},
    {"french": "le garage", "english": "garage", "spanish": "el garaje", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "garaje"},
    {"french": "l'escalier", "english": "stairs", "spanish": "la escalera", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "escalera"},
    {"french": "l'étage", "english": "floor/story", "spanish": "el piso", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "le sous-sol", "english": "basement", "spanish": "el sótano", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "le grenier", "english": "attic", "spanish": "el ático", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "la porte", "english": "door", "spanish": "la puerta", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "puerta"},
    {"french": "la fenêtre", "english": "window", "spanish": "la ventana", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "le mur", "english": "wall", "spanish": "el muro", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "muro"},
    {"french": "le plafond", "english": "ceiling", "spanish": "el techo", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "le sol", "english": "floor/ground", "spanish": "el suelo", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "suelo"},
    {"french": "le meuble", "english": "furniture", "spanish": "el mueble", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "mueble"},
    {"french": "le lit", "english": "bed", "spanish": "la cama", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "l'armoire", "english": "wardrobe", "spanish": "el armario", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "armario"},
    {"french": "la table", "english": "table", "spanish": "la mesa", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": True, "cognate_spanish": "tabla"},
    {"french": "la chaise", "english": "chair", "spanish": "la silla", "gender": "f", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "le canapé", "english": "sofa", "spanish": "el sofá", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": False},
    {"french": "le tapis", "english": "rug/carpet", "spanish": "la alfombra", "gender": "m", "part_of_speech": "noun", "category": "house", "is_cognate": False},

    # Food & Cooking (25 items)
    {"french": "le repas", "english": "meal", "spanish": "la comida", "gender": "m", "part_of_speech": "noun", "category": "food", "is_cognate": False},
    {"french": "le déjeuner", "english": "lunch", "spanish": "el almuerzo", "gender": "m", "part_of_speech": "noun", "category": "food", "is_cognate": False},
    {"french": "le dîner", "english": "dinner", "spanish": "la cena", "gender": "m", "part_of_speech": "noun", "category": "food", "is_cognate": False},
    {"french": "le goûter", "english": "snack (afternoon)", "spanish": "la merienda", "gender": "m", "part_of_speech": "noun", "category": "food", "is_cognate": False},
    {"french": "cuisiner", "english": "to cook", "spanish": "cocinar", "gender": "-", "part_of_speech": "verb", "category": "food", "is_cognate": True, "cognate_spanish": "cocinar"},
    {"french": "préparer", "english": "to prepare", "spanish": "preparar", "gender": "-", "part_of_speech": "verb", "category": "food", "is_cognate": True, "cognate_spanish": "preparar"},
    {"french": "couper", "english": "to cut", "spanish": "cortar", "gender": "-", "part_of_speech": "verb", "category": "food", "is_cognate": False},
    {"french": "mélanger", "english": "to mix", "spanish": "mezclar", "gender": "-", "part_of_speech": "verb", "category": "food", "is_cognate": False},
    {"french": "faire cuire", "english": "to cook (something)", "spanish": "cocinar", "gender": "-", "part_of_speech": "phrase", "category": "food", "is_cognate": False},
    {"french": "bouillir", "english": "to boil", "spanish": "hervir", "gender": "-", "part_of_speech": "verb", "category": "food", "is_cognate": False},
    {"french": "frire", "english": "to fry", "spanish": "freír", "gender": "-", "part_of_speech": "verb", "category": "food", "is_cognate": True, "cognate_spanish": "freír"},
    {"french": "la recette", "english": "recipe", "spanish": "la receta", "gender": "f", "part_of_speech": "noun", "category": "food", "is_cognate": True, "cognate_spanish": "receta"},
    {"french": "l'ingrédient", "english": "ingredient", "spanish": "el ingrediente", "gender": "m", "part_of_speech": "noun", "category": "food", "is_cognate": True, "cognate_spanish": "ingrediente"},
    {"french": "la casserole", "english": "saucepan", "spanish": "la cacerola", "gender": "f", "part_of_speech": "noun", "category": "food", "is_cognate": True, "cognate_spanish": "cacerola"},
    {"french": "la poêle", "english": "frying pan", "spanish": "la sartén", "gender": "f", "part_of_speech": "noun", "category": "food", "is_cognate": False},
    {"french": "le four", "english": "oven", "spanish": "el horno", "gender": "m", "part_of_speech": "noun", "category": "food", "is_cognate": False},
    {"french": "le réfrigérateur", "english": "refrigerator", "spanish": "el refrigerador", "gender": "m", "part_of_speech": "noun", "category": "food", "is_cognate": True, "cognate_spanish": "refrigerador"},
    {"french": "le congélateur", "english": "freezer", "spanish": "el congelador", "gender": "m", "part_of_speech": "noun", "category": "food", "is_cognate": True, "cognate_spanish": "congelador"},
    {"french": "délicieux", "english": "delicious", "spanish": "delicioso", "gender": "m", "part_of_speech": "adjective", "category": "food", "is_cognate": True, "cognate_spanish": "delicioso"},
    {"french": "salé", "english": "salty", "spanish": "salado", "gender": "m", "part_of_speech": "adjective", "category": "food", "is_cognate": True, "cognate_spanish": "salado"},
    {"french": "sucré", "english": "sweet", "spanish": "dulce", "gender": "m", "part_of_speech": "adjective", "category": "food", "is_cognate": False},
    {"french": "épicé", "english": "spicy", "spanish": "picante", "gender": "m", "part_of_speech": "adjective", "category": "food", "is_cognate": False},
    {"french": "amer", "english": "bitter", "spanish": "amargo", "gender": "m", "part_of_speech": "adjective", "category": "food", "is_cognate": True, "cognate_spanish": "amargo"},
    {"french": "acide", "english": "sour", "spanish": "ácido", "gender": "-", "part_of_speech": "adjective", "category": "food", "is_cognate": True, "cognate_spanish": "ácido"},
    {"french": "cru", "english": "raw", "spanish": "crudo", "gender": "m", "part_of_speech": "adjective", "category": "food", "is_cognate": True, "cognate_spanish": "crudo"},

    # Leisure & Hobbies (20 items)
    {"french": "le loisir", "english": "leisure/hobby", "spanish": "el ocio", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": False},
    {"french": "le passe-temps", "english": "hobby/pastime", "spanish": "el pasatiempo", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "pasatiempo"},
    {"french": "se détendre", "english": "to relax", "spanish": "relajarse", "gender": "-", "part_of_speech": "verb", "category": "leisure", "is_cognate": False},
    {"french": "s'amuser", "english": "to have fun", "spanish": "divertirse", "gender": "-", "part_of_speech": "verb", "category": "leisure", "is_cognate": False},
    {"french": "jouer", "english": "to play", "spanish": "jugar", "gender": "-", "part_of_speech": "verb", "category": "leisure", "is_cognate": False},
    {"french": "le sport", "english": "sport", "spanish": "el deporte", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "deporte"},
    {"french": "la natation", "english": "swimming", "spanish": "la natación", "gender": "f", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "natación"},
    {"french": "le football", "english": "soccer", "spanish": "el fútbol", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "fútbol"},
    {"french": "le tennis", "english": "tennis", "spanish": "el tenis", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "tenis"},
    {"french": "la randonnée", "english": "hiking", "spanish": "el senderismo", "gender": "f", "part_of_speech": "noun", "category": "leisure", "is_cognate": False},
    {"french": "la lecture", "english": "reading", "spanish": "la lectura", "gender": "f", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "lectura"},
    {"french": "la musique", "english": "music", "spanish": "la música", "gender": "f", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "música"},
    {"french": "le cinéma", "english": "cinema/movies", "spanish": "el cine", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "cine"},
    {"french": "le théâtre", "english": "theater", "spanish": "el teatro", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "teatro"},
    {"french": "le jardinage", "english": "gardening", "spanish": "la jardinería", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "jardinería"},
    {"french": "la peinture", "english": "painting", "spanish": "la pintura", "gender": "f", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "pintura"},
    {"french": "le dessin", "english": "drawing", "spanish": "el dibujo", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": False},
    {"french": "la photographie", "english": "photography", "spanish": "la fotografía", "gender": "f", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "fotografía"},
    {"french": "le voyage", "english": "travel/trip", "spanish": "el viaje", "gender": "m", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "viaje"},
    {"french": "les vacances", "english": "vacation", "spanish": "las vacaciones", "gender": "f", "part_of_speech": "noun", "category": "leisure", "is_cognate": True, "cognate_spanish": "vacaciones"},

    # Emotions & Feelings (15 items)
    {"french": "content", "english": "happy/pleased", "spanish": "contento", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "contento"},
    {"french": "triste", "english": "sad", "spanish": "triste", "gender": "-", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "triste"},
    {"french": "fatigué", "english": "tired", "spanish": "cansado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "en colère", "english": "angry", "spanish": "enfadado", "gender": "-", "part_of_speech": "phrase", "category": "emotions", "is_cognate": False},
    {"french": "surpris", "english": "surprised", "spanish": "sorprendido", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "sorprendido"},
    {"french": "inquiet", "english": "worried", "spanish": "preocupado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "nerveux", "english": "nervous", "spanish": "nervioso", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "nervioso"},
    {"french": "calme", "english": "calm", "spanish": "tranquilo", "gender": "-", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "calma"},
    {"french": "excité", "english": "excited", "spanish": "emocionado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "excitado"},
    {"french": "ennuyé", "english": "bored", "spanish": "aburrido", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "amoureux", "english": "in love", "spanish": "enamorado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "amoroso"},
    {"french": "jaloux", "english": "jealous", "spanish": "celoso", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "fier", "english": "proud", "spanish": "orgulloso", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
    {"french": "déçu", "english": "disappointed", "spanish": "decepcionado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": True, "cognate_spanish": "decepcionado"},
    {"french": "soulagé", "english": "relieved", "spanish": "aliviado", "gender": "m", "part_of_speech": "adjective", "category": "emotions", "is_cognate": False},
]
