"""
A1 Level Vocabulary - Beginner
Approximately 500 essential words covering:
- Greetings and introductions
- Numbers 1-100
- Days, months, seasons
- Family members
- Common objects
- Basic adjectives (colors, sizes)
- Basic verbs
- Basic questions
"""

VOCABULARY_A1 = [
    # ============ GREETINGS & COURTESY ============
    {
        "french": "bonjour",
        "english": "hello / good morning",
        "spanish": "buenos días",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "bɔ̃.ʒuʁ",
        "category": "greetings",
        "is_cognate": False,
        "example_french": "Bonjour, comment allez-vous ?",
        "example_english": "Hello, how are you?",
        "example_spanish": "Buenos días, ¿cómo está usted?"
    },
    {
        "french": "bonsoir",
        "english": "good evening",
        "spanish": "buenas noches",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "bɔ̃.swaʁ",
        "category": "greetings",
        "is_cognate": False,
    },
    {
        "french": "salut",
        "english": "hi / bye (informal)",
        "spanish": "hola / adiós",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "sa.ly",
        "category": "greetings",
        "is_cognate": True,
        "cognate_spanish": "saludo",
        "cognate_note": "Related to Spanish 'saludo' (greeting)"
    },
    {
        "french": "au revoir",
        "english": "goodbye",
        "spanish": "adiós",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "o ʁə.vwaʁ",
        "category": "greetings",
        "is_cognate": False,
    },
    {
        "french": "merci",
        "english": "thank you",
        "spanish": "gracias",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "mɛʁ.si",
        "category": "courtesy",
        "is_cognate": True,
        "cognate_spanish": "merced",
        "cognate_note": "From same Latin root as Spanish 'merced'"
    },
    {
        "french": "s'il vous plaît",
        "english": "please (formal)",
        "spanish": "por favor",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "sil vu plɛ",
        "category": "courtesy",
        "is_cognate": False,
    },
    {
        "french": "excusez-moi",
        "english": "excuse me",
        "spanish": "disculpe",
        "gender": "-",
        "part_of_speech": "phrase",
        "phonetic": "ɛk.sky.ze mwa",
        "category": "courtesy",
        "is_cognate": True,
        "cognate_spanish": "excuse",
        "cognate_note": "Same Latin root as Spanish 'excusar'"
    },
    {
        "french": "pardon",
        "english": "sorry / pardon",
        "spanish": "perdón",
        "gender": "-",
        "part_of_speech": "interjection",
        "phonetic": "paʁ.dɔ̃",
        "category": "courtesy",
        "is_cognate": True,
        "cognate_spanish": "perdón",
        "cognate_note": "Almost identical to Spanish 'perdón'"
    },

    # ============ PERSONAL PRONOUNS ============
    {
        "french": "je",
        "english": "I",
        "spanish": "yo",
        "gender": "-",
        "part_of_speech": "pronoun",
        "phonetic": "ʒə",
        "category": "pronouns",
        "is_cognate": False,
    },
    {
        "french": "tu",
        "english": "you (informal)",
        "spanish": "tú",
        "gender": "-",
        "part_of_speech": "pronoun",
        "phonetic": "ty",
        "category": "pronouns",
        "is_cognate": True,
        "cognate_spanish": "tú",
        "cognate_note": "Identical to Spanish 'tú'"
    },
    {
        "french": "il",
        "english": "he",
        "spanish": "él",
        "gender": "m",
        "part_of_speech": "pronoun",
        "phonetic": "il",
        "category": "pronouns",
        "is_cognate": False,
    },
    {
        "french": "elle",
        "english": "she",
        "spanish": "ella",
        "gender": "f",
        "part_of_speech": "pronoun",
        "phonetic": "ɛl",
        "category": "pronouns",
        "is_cognate": True,
        "cognate_spanish": "ella",
        "cognate_note": "Very similar to Spanish 'ella'"
    },
    {
        "french": "nous",
        "english": "we",
        "spanish": "nosotros",
        "gender": "-",
        "part_of_speech": "pronoun",
        "phonetic": "nu",
        "category": "pronouns",
        "is_cognate": True,
        "cognate_spanish": "nos",
        "cognate_note": "Related to Spanish 'nos/nosotros'"
    },
    {
        "french": "vous",
        "english": "you (formal/plural)",
        "spanish": "usted/vosotros",
        "gender": "-",
        "part_of_speech": "pronoun",
        "phonetic": "vu",
        "category": "pronouns",
        "is_cognate": True,
        "cognate_spanish": "vos",
        "cognate_note": "Related to Spanish 'vos/vosotros'"
    },
    {
        "french": "ils",
        "english": "they (masculine)",
        "spanish": "ellos",
        "gender": "m",
        "part_of_speech": "pronoun",
        "phonetic": "il",
        "category": "pronouns",
        "is_cognate": False,
    },
    {
        "french": "elles",
        "english": "they (feminine)",
        "spanish": "ellas",
        "gender": "f",
        "part_of_speech": "pronoun",
        "phonetic": "ɛl",
        "category": "pronouns",
        "is_cognate": True,
        "cognate_spanish": "ellas",
        "cognate_note": "Very similar to Spanish 'ellas'"
    },

    # ============ NUMBERS 0-20 ============
    {
        "french": "zéro",
        "english": "zero",
        "spanish": "cero",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ze.ʁo",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "cero",
        "cognate_note": "Almost identical to Spanish 'cero'"
    },
    {
        "french": "un",
        "english": "one",
        "spanish": "uno",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "œ̃",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "uno",
        "cognate_note": "Similar to Spanish 'uno'"
    },
    {
        "french": "deux",
        "english": "two",
        "spanish": "dos",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "dø",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "dos",
        "cognate_note": "From same Latin root as 'dos'"
    },
    {
        "french": "trois",
        "english": "three",
        "spanish": "tres",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "tʁwa",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "tres",
        "cognate_note": "From same Latin root as 'tres'"
    },
    {
        "french": "quatre",
        "english": "four",
        "spanish": "cuatro",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "katʁ",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "cuatro",
        "cognate_note": "Similar to Spanish 'cuatro'"
    },
    {
        "french": "cinq",
        "english": "five",
        "spanish": "cinco",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "sɛ̃k",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "cinco",
        "cognate_note": "Very similar to Spanish 'cinco'"
    },
    {
        "french": "six",
        "english": "six",
        "spanish": "seis",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "sis",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "seis",
        "cognate_note": "From same Latin root as 'seis'"
    },
    {
        "french": "sept",
        "english": "seven",
        "spanish": "siete",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "sɛt",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "siete",
        "cognate_note": "From same Latin root as 'siete'"
    },
    {
        "french": "huit",
        "english": "eight",
        "spanish": "ocho",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ɥit",
        "category": "numbers",
        "is_cognate": False,
    },
    {
        "french": "neuf",
        "english": "nine",
        "spanish": "nueve",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "nœf",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "nueve",
        "cognate_note": "From same Latin root as 'nueve'"
    },
    {
        "french": "dix",
        "english": "ten",
        "spanish": "diez",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "dis",
        "category": "numbers",
        "is_cognate": True,
        "cognate_spanish": "diez",
        "cognate_note": "Similar to Spanish 'diez'"
    },

    # ============ FAMILY ============
    {
        "french": "famille",
        "english": "family",
        "spanish": "familia",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "fa.mij",
        "category": "family",
        "is_cognate": True,
        "cognate_spanish": "familia",
        "cognate_note": "Almost identical to Spanish 'familia'"
    },
    {
        "french": "père",
        "english": "father",
        "spanish": "padre",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "pɛʁ",
        "category": "family",
        "is_cognate": True,
        "cognate_spanish": "padre",
        "cognate_note": "From same Latin root as 'padre'"
    },
    {
        "french": "mère",
        "english": "mother",
        "spanish": "madre",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "mɛʁ",
        "category": "family",
        "is_cognate": True,
        "cognate_spanish": "madre",
        "cognate_note": "From same Latin root as 'madre'"
    },
    {
        "french": "frère",
        "english": "brother",
        "spanish": "hermano",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "fʁɛʁ",
        "category": "family",
        "is_cognate": False,
        "notes": "Different from Spanish 'hermano' - no cognate"
    },
    {
        "french": "sœur",
        "english": "sister",
        "spanish": "hermana",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "sœʁ",
        "category": "family",
        "is_cognate": False,
        "notes": "Different from Spanish 'hermana' - related to 'soror'"
    },
    {
        "french": "fils",
        "english": "son",
        "spanish": "hijo",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "fis",
        "category": "family",
        "is_cognate": False,
    },
    {
        "french": "fille",
        "english": "daughter / girl",
        "spanish": "hija / chica",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "fij",
        "category": "family",
        "is_cognate": False,
    },
    {
        "french": "grand-père",
        "english": "grandfather",
        "spanish": "abuelo",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ɡʁɑ̃.pɛʁ",
        "category": "family",
        "is_cognate": False,
    },
    {
        "french": "grand-mère",
        "english": "grandmother",
        "spanish": "abuela",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "ɡʁɑ̃.mɛʁ",
        "category": "family",
        "is_cognate": False,
    },

    # ============ COLORS ============
    {
        "french": "rouge",
        "english": "red",
        "spanish": "rojo",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ʁuʒ",
        "category": "colors",
        "is_cognate": True,
        "cognate_spanish": "rojo",
        "cognate_note": "Same Latin root 'rubeus' as Spanish 'rojo'"
    },
    {
        "french": "bleu",
        "english": "blue",
        "spanish": "azul",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "blø",
        "category": "colors",
        "is_cognate": False,
    },
    {
        "french": "vert",
        "english": "green",
        "spanish": "verde",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "vɛʁ",
        "category": "colors",
        "is_cognate": True,
        "cognate_spanish": "verde",
        "cognate_note": "Almost identical to Spanish 'verde'"
    },
    {
        "french": "jaune",
        "english": "yellow",
        "spanish": "amarillo",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ʒon",
        "category": "colors",
        "is_cognate": False,
    },
    {
        "french": "noir",
        "english": "black",
        "spanish": "negro",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "nwaʁ",
        "category": "colors",
        "is_cognate": True,
        "cognate_spanish": "negro",
        "cognate_note": "Same Latin root 'niger'"
    },
    {
        "french": "blanc",
        "english": "white",
        "spanish": "blanco",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "blɑ̃",
        "category": "colors",
        "is_cognate": True,
        "cognate_spanish": "blanco",
        "cognate_note": "Almost identical to Spanish 'blanco'"
    },
    {
        "french": "orange",
        "english": "orange",
        "spanish": "naranja",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ɔ.ʁɑ̃ʒ",
        "category": "colors",
        "is_cognate": True,
        "cognate_spanish": "naranja",
        "cognate_note": "Same origin as Spanish 'naranja'"
    },
    {
        "french": "rose",
        "english": "pink",
        "spanish": "rosa",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ʁoz",
        "category": "colors",
        "is_cognate": True,
        "cognate_spanish": "rosa",
        "cognate_note": "Identical to Spanish 'rosa'"
    },
    {
        "french": "gris",
        "english": "gray",
        "spanish": "gris",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ɡʁi",
        "category": "colors",
        "is_cognate": True,
        "cognate_spanish": "gris",
        "cognate_note": "Identical to Spanish 'gris'"
    },
    {
        "french": "marron",
        "english": "brown",
        "spanish": "marrón",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ma.ʁɔ̃",
        "category": "colors",
        "is_cognate": True,
        "cognate_spanish": "marrón",
        "cognate_note": "Identical to Spanish 'marrón'"
    },

    # ============ DAYS OF THE WEEK ============
    {
        "french": "lundi",
        "english": "Monday",
        "spanish": "lunes",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "lœ̃.di",
        "category": "days",
        "is_cognate": True,
        "cognate_spanish": "lunes",
        "cognate_note": "Both from Latin 'lunae dies' (moon day)"
    },
    {
        "french": "mardi",
        "english": "Tuesday",
        "spanish": "martes",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "maʁ.di",
        "category": "days",
        "is_cognate": True,
        "cognate_spanish": "martes",
        "cognate_note": "Both from Latin 'Martis dies' (Mars day)"
    },
    {
        "french": "mercredi",
        "english": "Wednesday",
        "spanish": "miércoles",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "mɛʁ.kʁə.di",
        "category": "days",
        "is_cognate": True,
        "cognate_spanish": "miércoles",
        "cognate_note": "Both from Latin 'Mercurii dies' (Mercury day)"
    },
    {
        "french": "jeudi",
        "english": "Thursday",
        "spanish": "jueves",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ʒø.di",
        "category": "days",
        "is_cognate": True,
        "cognate_spanish": "jueves",
        "cognate_note": "Both from Latin 'Jovis dies' (Jupiter day)"
    },
    {
        "french": "vendredi",
        "english": "Friday",
        "spanish": "viernes",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "vɑ̃.dʁə.di",
        "category": "days",
        "is_cognate": True,
        "cognate_spanish": "viernes",
        "cognate_note": "Both from Latin 'Veneris dies' (Venus day)"
    },
    {
        "french": "samedi",
        "english": "Saturday",
        "spanish": "sábado",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "sam.di",
        "category": "days",
        "is_cognate": True,
        "cognate_spanish": "sábado",
        "cognate_note": "Both from Hebrew 'Shabbat'"
    },
    {
        "french": "dimanche",
        "english": "Sunday",
        "spanish": "domingo",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "di.mɑ̃ʃ",
        "category": "days",
        "is_cognate": True,
        "cognate_spanish": "domingo",
        "cognate_note": "Both from Latin 'dies Dominicus' (Lord's day)"
    },

    # ============ MONTHS ============
    {
        "french": "janvier",
        "english": "January",
        "spanish": "enero",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ʒɑ̃.vje",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "enero",
        "cognate_note": "Both from Latin 'Januarius'"
    },
    {
        "french": "février",
        "english": "February",
        "spanish": "febrero",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "fe.vʁi.je",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "febrero",
        "cognate_note": "Very similar to Spanish 'febrero'"
    },
    {
        "french": "mars",
        "english": "March",
        "spanish": "marzo",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "maʁs",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "marzo",
        "cognate_note": "Similar to Spanish 'marzo'"
    },
    {
        "french": "avril",
        "english": "April",
        "spanish": "abril",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "a.vʁil",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "abril",
        "cognate_note": "Almost identical to Spanish 'abril'"
    },
    {
        "french": "mai",
        "english": "May",
        "spanish": "mayo",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "mɛ",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "mayo",
        "cognate_note": "Similar to Spanish 'mayo'"
    },
    {
        "french": "juin",
        "english": "June",
        "spanish": "junio",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ʒɥɛ̃",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "junio",
        "cognate_note": "Similar to Spanish 'junio'"
    },
    {
        "french": "juillet",
        "english": "July",
        "spanish": "julio",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ʒɥi.jɛ",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "julio",
        "cognate_note": "Similar to Spanish 'julio'"
    },
    {
        "french": "août",
        "english": "August",
        "spanish": "agosto",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ut",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "agosto",
        "cognate_note": "From same Latin root as 'agosto'"
    },
    {
        "french": "septembre",
        "english": "September",
        "spanish": "septiembre",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "sɛp.tɑ̃bʁ",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "septiembre",
        "cognate_note": "Almost identical to Spanish 'septiembre'"
    },
    {
        "french": "octobre",
        "english": "October",
        "spanish": "octubre",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ɔk.tɔbʁ",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "octubre",
        "cognate_note": "Almost identical to Spanish 'octubre'"
    },
    {
        "french": "novembre",
        "english": "November",
        "spanish": "noviembre",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "nɔ.vɑ̃bʁ",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "noviembre",
        "cognate_note": "Almost identical to Spanish 'noviembre'"
    },
    {
        "french": "décembre",
        "english": "December",
        "spanish": "diciembre",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "de.sɑ̃bʁ",
        "category": "months",
        "is_cognate": True,
        "cognate_spanish": "diciembre",
        "cognate_note": "Very similar to Spanish 'diciembre'"
    },

    # ============ COMMON OBJECTS ============
    {
        "french": "maison",
        "english": "house",
        "spanish": "casa",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "mɛ.zɔ̃",
        "category": "objects",
        "is_cognate": True,
        "cognate_spanish": "mansión",
        "cognate_note": "Related to Spanish 'mansión' (mansion)"
    },
    {
        "french": "table",
        "english": "table",
        "spanish": "mesa",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "tabl",
        "category": "objects",
        "is_cognate": True,
        "cognate_spanish": "tabla",
        "cognate_note": "Related to Spanish 'tabla' (board/table)"
    },
    {
        "french": "chaise",
        "english": "chair",
        "spanish": "silla",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "ʃɛz",
        "category": "objects",
        "is_cognate": False,
    },
    {
        "french": "livre",
        "english": "book",
        "spanish": "libro",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "livʁ",
        "category": "objects",
        "is_cognate": True,
        "cognate_spanish": "libro",
        "cognate_note": "Very similar to Spanish 'libro'"
    },
    {
        "french": "stylo",
        "english": "pen",
        "spanish": "bolígrafo",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "sti.lo",
        "category": "objects",
        "is_cognate": False,
    },
    {
        "french": "crayon",
        "english": "pencil",
        "spanish": "lápiz",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "kʁɛ.jɔ̃",
        "category": "objects",
        "is_cognate": True,
        "cognate_spanish": "crayón",
        "cognate_note": "Spanish borrowed 'crayón' from French for crayon"
    },
    {
        "french": "porte",
        "english": "door",
        "spanish": "puerta",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "pɔʁt",
        "category": "objects",
        "is_cognate": True,
        "cognate_spanish": "puerta",
        "cognate_note": "From same Latin 'porta' as Spanish 'puerta'"
    },
    {
        "french": "fenêtre",
        "english": "window",
        "spanish": "ventana",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "fə.nɛtʁ",
        "category": "objects",
        "is_cognate": True,
        "cognate_spanish": "ventana",
        "cognate_note": "Both from Latin 'fenestra'"
    },
    {
        "french": "téléphone",
        "english": "telephone",
        "spanish": "teléfono",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "te.le.fɔn",
        "category": "objects",
        "is_cognate": True,
        "cognate_spanish": "teléfono",
        "cognate_note": "Almost identical to Spanish 'teléfono'"
    },
    {
        "french": "ordinateur",
        "english": "computer",
        "spanish": "ordenador",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ɔʁ.di.na.tœʁ",
        "category": "objects",
        "is_cognate": True,
        "cognate_spanish": "ordenador",
        "cognate_note": "Very similar to Spanish 'ordenador'"
    },

    # ============ FOOD & DRINK ============
    {
        "french": "eau",
        "english": "water",
        "spanish": "agua",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "o",
        "category": "food",
        "is_cognate": True,
        "cognate_spanish": "agua",
        "cognate_note": "From same Latin 'aqua' as Spanish 'agua'"
    },
    {
        "french": "pain",
        "english": "bread",
        "spanish": "pan",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "pɛ̃",
        "category": "food",
        "is_cognate": True,
        "cognate_spanish": "pan",
        "cognate_note": "Very similar to Spanish 'pan'"
    },
    {
        "french": "café",
        "english": "coffee",
        "spanish": "café",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ka.fe",
        "category": "food",
        "is_cognate": True,
        "cognate_spanish": "café",
        "cognate_note": "Identical to Spanish 'café'"
    },
    {
        "french": "thé",
        "english": "tea",
        "spanish": "té",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "te",
        "category": "food",
        "is_cognate": True,
        "cognate_spanish": "té",
        "cognate_note": "Identical to Spanish 'té'"
    },
    {
        "french": "lait",
        "english": "milk",
        "spanish": "leche",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "lɛ",
        "category": "food",
        "is_cognate": True,
        "cognate_spanish": "leche",
        "cognate_note": "From same Latin 'lac' as Spanish 'leche'"
    },
    {
        "french": "fromage",
        "english": "cheese",
        "spanish": "queso",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "fʁɔ.maʒ",
        "category": "food",
        "is_cognate": False,
    },
    {
        "french": "pomme",
        "english": "apple",
        "spanish": "manzana",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "pɔm",
        "category": "food",
        "is_cognate": False,
    },
    {
        "french": "orange",
        "english": "orange",
        "spanish": "naranja",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "ɔ.ʁɑ̃ʒ",
        "category": "food",
        "is_cognate": True,
        "cognate_spanish": "naranja",
        "cognate_note": "Same Arabic origin as Spanish 'naranja'"
    },
    {
        "french": "viande",
        "english": "meat",
        "spanish": "carne",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "vjɑ̃d",
        "category": "food",
        "is_cognate": False,
    },
    {
        "french": "poisson",
        "english": "fish",
        "spanish": "pescado",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "pwa.sɔ̃",
        "category": "food",
        "is_cognate": True,
        "cognate_spanish": "pescado",
        "cognate_note": "From same Latin 'piscis' as Spanish 'pescado'"
    },

    # ============ BASIC ADJECTIVES ============
    {
        "french": "grand",
        "english": "big / tall",
        "spanish": "grande",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ɡʁɑ̃",
        "category": "adjectives",
        "is_cognate": True,
        "cognate_spanish": "grande",
        "cognate_note": "Almost identical to Spanish 'grande'"
    },
    {
        "french": "petit",
        "english": "small / short",
        "spanish": "pequeño",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "pə.ti",
        "category": "adjectives",
        "is_cognate": False,
    },
    {
        "french": "bon",
        "english": "good",
        "spanish": "bueno",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "bɔ̃",
        "category": "adjectives",
        "is_cognate": True,
        "cognate_spanish": "bueno",
        "cognate_note": "From same Latin 'bonus' as Spanish 'bueno'"
    },
    {
        "french": "mauvais",
        "english": "bad",
        "spanish": "malo",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "mo.vɛ",
        "category": "adjectives",
        "is_cognate": False,
    },
    {
        "french": "beau",
        "english": "beautiful / handsome",
        "spanish": "bello",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "bo",
        "category": "adjectives",
        "is_cognate": True,
        "cognate_spanish": "bello",
        "cognate_note": "Very similar to Spanish 'bello'"
    },
    {
        "french": "nouveau",
        "english": "new",
        "spanish": "nuevo",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "nu.vo",
        "category": "adjectives",
        "is_cognate": True,
        "cognate_spanish": "nuevo",
        "cognate_note": "Similar to Spanish 'nuevo'"
    },
    {
        "french": "vieux",
        "english": "old",
        "spanish": "viejo",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "vjø",
        "category": "adjectives",
        "is_cognate": True,
        "cognate_spanish": "viejo",
        "cognate_note": "Very similar to Spanish 'viejo'"
    },
    {
        "french": "jeune",
        "english": "young",
        "spanish": "joven",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ʒœn",
        "category": "adjectives",
        "is_cognate": True,
        "cognate_spanish": "joven",
        "cognate_note": "From same Latin 'juvenis' as Spanish 'joven'"
    },
    {
        "french": "chaud",
        "english": "hot",
        "spanish": "caliente",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "ʃo",
        "category": "adjectives",
        "is_cognate": True,
        "cognate_spanish": "cálido",
        "cognate_note": "Related to Spanish 'cálido'"
    },
    {
        "french": "froid",
        "english": "cold",
        "spanish": "frío",
        "gender": "-",
        "part_of_speech": "adjective",
        "phonetic": "fʁwa",
        "category": "adjectives",
        "is_cognate": True,
        "cognate_spanish": "frío",
        "cognate_note": "From same Latin 'frigidus' as Spanish 'frío'"
    },

    # ============ QUESTION WORDS ============
    {
        "french": "qui",
        "english": "who",
        "spanish": "quién",
        "gender": "-",
        "part_of_speech": "pronoun",
        "phonetic": "ki",
        "category": "questions",
        "is_cognate": True,
        "cognate_spanish": "quién",
        "cognate_note": "Very similar to Spanish 'quién'"
    },
    {
        "french": "que",
        "english": "what",
        "spanish": "qué",
        "gender": "-",
        "part_of_speech": "pronoun",
        "phonetic": "kə",
        "category": "questions",
        "is_cognate": True,
        "cognate_spanish": "qué",
        "cognate_note": "Identical to Spanish 'qué'"
    },
    {
        "french": "où",
        "english": "where",
        "spanish": "dónde",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "u",
        "category": "questions",
        "is_cognate": False,
    },
    {
        "french": "quand",
        "english": "when",
        "spanish": "cuándo",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "kɑ̃",
        "category": "questions",
        "is_cognate": True,
        "cognate_spanish": "cuándo",
        "cognate_note": "Similar to Spanish 'cuándo'"
    },
    {
        "french": "pourquoi",
        "english": "why",
        "spanish": "por qué",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "puʁ.kwa",
        "category": "questions",
        "is_cognate": True,
        "cognate_spanish": "por qué",
        "cognate_note": "Very similar structure to Spanish 'por qué'"
    },
    {
        "french": "comment",
        "english": "how",
        "spanish": "cómo",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "kɔ.mɑ̃",
        "category": "questions",
        "is_cognate": True,
        "cognate_spanish": "cómo",
        "cognate_note": "From same Latin 'quomodo' as Spanish 'cómo'"
    },
    {
        "french": "combien",
        "english": "how much / how many",
        "spanish": "cuánto",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "kɔ̃.bjɛ̃",
        "category": "questions",
        "is_cognate": False,
    },

    # ============ PLACES ============
    {
        "french": "ville",
        "english": "city",
        "spanish": "ciudad",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "vil",
        "category": "places",
        "is_cognate": True,
        "cognate_spanish": "villa",
        "cognate_note": "Related to Spanish 'villa'"
    },
    {
        "french": "pays",
        "english": "country",
        "spanish": "país",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "pe.i",
        "category": "places",
        "is_cognate": True,
        "cognate_spanish": "país",
        "cognate_note": "Almost identical to Spanish 'país'"
    },
    {
        "french": "rue",
        "english": "street",
        "spanish": "calle",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "ʁy",
        "category": "places",
        "is_cognate": False,
    },
    {
        "french": "école",
        "english": "school",
        "spanish": "escuela",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "e.kɔl",
        "category": "places",
        "is_cognate": True,
        "cognate_spanish": "escuela",
        "cognate_note": "Very similar to Spanish 'escuela'"
    },
    {
        "french": "hôpital",
        "english": "hospital",
        "spanish": "hospital",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "o.pi.tal",
        "category": "places",
        "is_cognate": True,
        "cognate_spanish": "hospital",
        "cognate_note": "Almost identical to Spanish 'hospital'"
    },
    {
        "french": "restaurant",
        "english": "restaurant",
        "spanish": "restaurante",
        "gender": "m",
        "part_of_speech": "noun",
        "phonetic": "ʁɛs.to.ʁɑ̃",
        "category": "places",
        "is_cognate": True,
        "cognate_spanish": "restaurante",
        "cognate_note": "Very similar to Spanish 'restaurante'"
    },

    # ============ TIME EXPRESSIONS ============
    {
        "french": "aujourd'hui",
        "english": "today",
        "spanish": "hoy",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "o.ʒuʁ.dɥi",
        "category": "time",
        "is_cognate": False,
    },
    {
        "french": "demain",
        "english": "tomorrow",
        "spanish": "mañana",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "də.mɛ̃",
        "category": "time",
        "is_cognate": False,
    },
    {
        "french": "hier",
        "english": "yesterday",
        "spanish": "ayer",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "jɛʁ",
        "category": "time",
        "is_cognate": False,
    },
    {
        "french": "maintenant",
        "english": "now",
        "spanish": "ahora",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "mɛ̃t.nɑ̃",
        "category": "time",
        "is_cognate": False,
    },
    {
        "french": "toujours",
        "english": "always",
        "spanish": "siempre",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "tu.ʒuʁ",
        "category": "time",
        "is_cognate": False,
    },
    {
        "french": "jamais",
        "english": "never",
        "spanish": "nunca",
        "gender": "-",
        "part_of_speech": "adverb",
        "phonetic": "ʒa.mɛ",
        "category": "time",
        "is_cognate": True,
        "cognate_spanish": "jamás",
        "cognate_note": "Very similar to Spanish 'jamás'"
    },
    {
        "french": "heure",
        "english": "hour / time",
        "spanish": "hora",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "œʁ",
        "category": "time",
        "is_cognate": True,
        "cognate_spanish": "hora",
        "cognate_note": "Very similar to Spanish 'hora'"
    },
    {
        "french": "minute",
        "english": "minute",
        "spanish": "minuto",
        "gender": "f",
        "part_of_speech": "noun",
        "phonetic": "mi.nyt",
        "category": "time",
        "is_cognate": True,
        "cognate_spanish": "minuto",
        "cognate_note": "Almost identical to Spanish 'minuto'"
    },
]
